(function(){
  "use strict";
  if(window.safelightAdjustToolsLoaded)return;
  window.safelightAdjustToolsLoaded=true;

  const $=id=>document.getElementById(id);
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  let sourceImage=null;
  let sourceSrc="";
  let renderTimer=0;
  let renderToken=0;
  let lastCanvas=null;
  let exporting=false;

  function active(){return !!document.querySelector("#panel-adjust.active")}
  function number(id,fallback){const value=Number($(id)?.value);return Number.isFinite(value)?value:fallback}
  function state(){return{
    exposure:clamp(number("a-exposure",0),-2,2),brightness:clamp(number("a-bright",0),-100,100),contrast:clamp(number("a-contrast",0),-100,100),
    highlights:clamp(number("a-highlights",0),-100,100),shadows:clamp(number("a-shadows",0),-100,100),temperature:clamp(number("a-temp",0),-100,100),
    tint:clamp(number("a-tint",0),-100,100),saturation:clamp(number("a-sat",0),-100,100),gamma:clamp(number("a-gamma",1),0.5,2),
    sharpness:clamp(number("a-sharp",0),0,100),blur:clamp(number("a-blur",0),0,20),vignette:clamp(number("a-vignette",0),0,100),
    sepia:clamp(number("a-sepia",0),0,100),grayscale:!!$("a-gray")?.checked
  }}
  function slider(id,label,min,max,value,step){return `<div class="slider-row sl-adjust-slider"><div class="top"><span>${label}</span><b id="${id}-val">${value}</b></div><input type="range" id="${id}" min="${min}" max="${max}" value="${value}"${step?` step="${step}"`:""}></div>`}

  function installPanel(){
    const panel=$("panel-adjust");if(!panel||panel.dataset.advancedAdjust==="1")return false;panel.dataset.advancedAdjust="1";
    panel.innerHTML=`<div class="panel-card sl-adjust-panel"><h2>РАСШИРЕННАЯ КОРРЕКЦИЯ</h2><p class="desc">Тон, цвет и детали изображения с живым предпросмотром. Все вычисления выполняются локально.</p>
      <div class="sl-adjust-section"><div class="sl-adjust-section-head"><span>Быстрый старт</span><small>пресеты не меняют оригинал</small></div><div class="sl-adjust-presets">
        <button type="button" class="btn ghost" data-adjust-preset="neutral">Нейтрально</button><button type="button" class="btn ghost" data-adjust-preset="vivid">Живее</button><button type="button" class="btn ghost" data-adjust-preset="warm">Теплее</button><button type="button" class="btn ghost" data-adjust-preset="cool">Холоднее</button><button type="button" class="btn ghost" data-adjust-preset="cinema">Кино</button><button type="button" class="btn ghost" data-adjust-preset="bw">Ч/Б</button>
      </div></div>
      <div class="sl-adjust-section"><div class="sl-adjust-section-head"><span>Свет</span><small>экспозиция и динамический диапазон</small></div>${slider("a-exposure","Экспозиция",-2,2,0,0.05)}${slider("a-bright","Яркость",-100,100,0,1)}${slider("a-contrast","Контраст",-100,100,0,1)}${slider("a-highlights","Света",-100,100,0,1)}${slider("a-shadows","Тени",-100,100,0,1)}</div>
      <div class="sl-adjust-section"><div class="sl-adjust-section-head"><span>Цвет</span><small>баланс белого и насыщенность</small></div>${slider("a-temp","Температура",-100,100,0,1)}${slider("a-tint","Оттенок",-100,100,0,1)}${slider("a-sat","Насыщенность",-100,100,0,1)}${slider("a-gamma","Гамма",0.5,2,1,0.01)}</div>
      <div class="sl-adjust-section"><div class="sl-adjust-section-head"><span>Детали и эффект</span><small>финальная обработка</small></div>${slider("a-sharp","Резкость",0,100,0,1)}${slider("a-blur","Размытие",0,20,0,0.25)}${slider("a-vignette","Виньетка",0,100,0,1)}${slider("a-sepia","Сепия",0,100,0,1)}<label class="check-row sl-adjust-check"><input type="checkbox" id="a-gray"> Чёрно-белое</label></div>
      <div class="sl-adjust-note">Экспорт использует именно текущий результат коррекции, включая HEIC и PDF.</div></div>`;
    bindPanel(panel);updateLabels();return true;
  }

  function fmtSigned(value){const n=Number(value)||0;return n>0?`+${n}`:String(n)}
  function updateLabels(){const set=(id,text)=>{const el=$(id+"-val");if(el)el.textContent=text};const ev=number("a-exposure",0);set("a-exposure",`${ev>0?"+":""}${ev.toFixed(2).replace(/\.?0+$/,'')} EV`);set("a-bright",fmtSigned(number("a-bright",0)));set("a-contrast",fmtSigned(number("a-contrast",0)));set("a-highlights",fmtSigned(number("a-highlights",0)));set("a-shadows",fmtSigned(number("a-shadows",0)));set("a-temp",fmtSigned(number("a-temp",0)));set("a-tint",fmtSigned(number("a-tint",0)));set("a-sat",fmtSigned(number("a-sat",0)));set("a-gamma",number("a-gamma",1).toFixed(2));set("a-sharp",number("a-sharp",0));set("a-blur",`${number("a-blur",0).toFixed(2).replace(/\.?0+$/,'')} px`);set("a-vignette",`${number("a-vignette",0)}%`);set("a-sepia",`${number("a-sepia",0)}%`)}

  const PRESETS={
    neutral:{exposure:0,bright:0,contrast:0,highlights:0,shadows:0,temp:0,tint:0,sat:0,gamma:1,sharp:0,blur:0,vignette:0,sepia:0,gray:false},
    vivid:{exposure:.1,bright:2,contrast:12,highlights:-6,shadows:10,temp:3,tint:0,sat:18,gamma:1,sharp:20,blur:0,vignette:6,sepia:0,gray:false},
    warm:{exposure:.05,bright:1,contrast:5,highlights:-8,shadows:10,temp:26,tint:5,sat:9,gamma:1.02,sharp:8,blur:0,vignette:4,sepia:0,gray:false},
    cool:{exposure:0,bright:0,contrast:7,highlights:-7,shadows:7,temp:-24,tint:-3,sat:5,gamma:1,sharp:10,blur:0,vignette:5,sepia:0,gray:false},
    cinema:{exposure:-.1,bright:0,contrast:18,highlights:-22,shadows:18,temp:-7,tint:7,sat:-8,gamma:.96,sharp:12,blur:0,vignette:24,sepia:5,gray:false},
    bw:{exposure:0,bright:0,contrast:14,highlights:-10,shadows:12,temp:0,tint:0,sat:-100,gamma:1,sharp:14,blur:0,vignette:16,sepia:0,gray:true}
  };
  function applyPreset(name){const p=PRESETS[name];if(!p)return;const values={"a-exposure":p.exposure,"a-bright":p.bright,"a-contrast":p.contrast,"a-highlights":p.highlights,"a-shadows":p.shadows,"a-temp":p.temp,"a-tint":p.tint,"a-sat":p.sat,"a-gamma":p.gamma,"a-sharp":p.sharp,"a-blur":p.blur,"a-vignette":p.vignette,"a-sepia":p.sepia};Object.entries(values).forEach(([id,value])=>{const el=$(id);if(el)el.value=String(value)});if($("a-gray"))$("a-gray").checked=!!p.gray;updateLabels();scheduleRender(0);document.querySelectorAll("[data-adjust-preset]").forEach(button=>button.classList.toggle("active",button.dataset.adjustPreset===name))}
  function bindPanel(panel){panel.addEventListener("input",event=>{if(!event.target.matches("input,select"))return;updateLabels();document.querySelectorAll("[data-adjust-preset]").forEach(button=>button.classList.remove("active"));scheduleRender()},true);panel.addEventListener("change",event=>{if(!event.target.matches("input,select"))return;updateLabels();scheduleRender(0)},true);panel.addEventListener("click",event=>{const preset=event.target.closest("[data-adjust-preset]");if(preset){event.preventDefault();applyPreset(preset.dataset.adjustPreset)}})}

  function loadSource(){const preview=$("previewImg"),src=preview?.src||"";if(!src){sourceImage=null;sourceSrc="";return Promise.resolve(null)}if(sourceImage&&sourceSrc===src)return Promise.resolve(sourceImage);return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{sourceImage=image;sourceSrc=src;resolve(image)};image.onerror=()=>reject(new Error("Не удалось открыть изображение"));image.src=src})}
  function gammaLut(gamma){const lut=new Uint8ClampedArray(256),inv=1/gamma;for(let i=0;i<256;i++)lut[i]=Math.round(255*Math.pow(i/255,inv));return lut}
  function tonePixels(canvas,s){const needsTone=Math.abs(s.gamma-1)>.001||s.temperature!==0||s.tint!==0||s.highlights!==0||s.shadows!==0;if(!needsTone)return;const ctx=canvas.getContext("2d",{willReadFrequently:true}),imageData=ctx.getImageData(0,0,canvas.width,canvas.height),data=imageData.data,lut=Math.abs(s.gamma-1)>.001?gammaLut(s.gamma):null,warm=s.temperature*.62,tint=s.tint;for(let i=0;i<data.length;i+=4){if(data[i+3]===0)continue;let r=data[i]+warm+tint*.24,g=data[i+1]-tint*.48,b=data[i+2]-warm+tint*.24;r=clamp(r,0,255);g=clamp(g,0,255);b=clamp(b,0,255);const lum=(.2126*r+.7152*g+.0722*b)/255,shadowWeight=(1-lum)*(1-lum),highlightWeight=lum*lum,delta=s.shadows*.72*shadowWeight+s.highlights*.72*highlightWeight;r=clamp(r+delta,0,255);g=clamp(g+delta,0,255);b=clamp(b+delta,0,255);if(lut){r=lut[Math.round(r)];g=lut[Math.round(g)];b=lut[Math.round(b)]}data[i]=r;data[i+1]=g;data[i+2]=b}ctx.putImageData(imageData,0,0)}
  function sharpen(canvas,amount){if(amount<=0||canvas.width<3||canvas.height<3)return;const ctx=canvas.getContext("2d",{willReadFrequently:true}),imageData=ctx.getImageData(0,0,canvas.width,canvas.height),data=imageData.data,src=new Uint8ClampedArray(data),w=canvas.width,h=canvas.height,strength=amount/100*.28,row=w*4;for(let y=1;y<h-1;y++){let i=(y*w+1)*4;for(let x=1;x<w-1;x++,i+=4){for(let c=0;c<3;c++){const center=src[i+c],lap=center*4-src[i-4+c]-src[i+4+c]-src[i-row+c]-src[i+row+c];data[i+c]=clamp(center+lap*strength,0,255)}}}ctx.putImageData(imageData,0,0)}
  function vignette(canvas,amount){if(amount<=0)return;const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height,cx=w/2,cy=h/2,radius=Math.sqrt(w*w+h*h)/2,gradient=ctx.createRadialGradient(cx,cy,radius*.34,cx,cy,radius);gradient.addColorStop(0,"rgba(0,0,0,0)");gradient.addColorStop(.56,"rgba(0,0,0,0)");gradient.addColorStop(1,`rgba(0,0,0,${amount/100*.78})`);ctx.save();ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);ctx.restore()}
  async function buildCanvas(){const image=await loadSource();if(!image)return null;const s=state(),canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const ctx=canvas.getContext("2d"),exposure=Math.pow(2,s.exposure),brightness=clamp(exposure*(1+s.brightness/100),0,4);ctx.filter=`brightness(${brightness}) contrast(${clamp(100+s.contrast,0,200)}%) saturate(${clamp(100+s.saturation,0,200)}%) blur(${s.blur}px) sepia(${s.sepia}%) grayscale(${s.grayscale?100:0}%)`;ctx.drawImage(image,0,0,canvas.width,canvas.height);ctx.filter="none";tonePixels(canvas,s);sharpen(canvas,s.sharpness);vignette(canvas,s.vignette);return canvas}
  function copyCanvas(input){const out=document.createElement("canvas");out.width=input.width;out.height=input.height;out.getContext("2d").drawImage(input,0,0);return out}
  async function renderNow(){if(!active())return null;const token=++renderToken;try{const built=await buildCanvas();if(!built||token!==renderToken||!active())return null;const live=$("sl-live-canvas");if(!live)return null;live.width=built.width;live.height=built.height;const ctx=live.getContext("2d");ctx.clearRect(0,0,live.width,live.height);ctx.drawImage(built,0,0);$("previewWrap")?.classList.add("sl-live-ready");lastCanvas=copyCanvas(built);if($("ro-dims"))$("ro-dims").textContent=`${built.width} × ${built.height} px`;if($("ro-format"))$("ro-format").textContent="LIVE";return lastCanvas}catch(error){console.error("Safelight advanced adjust:",error);return null}}
  function scheduleRender(delay){clearTimeout(renderTimer);renderTimer=setTimeout(renderNow,delay==null?85:delay)}
  function updateInspector(){if(!active())return;const title=$("sl-inspector-title"),desc=$("sl-inspector-desc");if(title)title.textContent="Расширенная коррекция";if(desc)desc.textContent="Экспозиция, свет, тени, баланс белого, гамма, резкость и эффекты."}

  function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Не удалось подготовить файл")),type,quality))}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
  function baseName(){return (($("meta-name")?.textContent||"safelight").trim().replace(/\.[^.]+$/,'')||"safelight")}
  function hint(text){const el=$("sl-export-hint");if(!el)return;el.textContent=text;el.classList.add("show");clearTimeout(hint.timer);hint.timer=setTimeout(()=>el.classList.remove("show"),3000)}
  async function exportAdjusted(format){if(exporting)return;exporting=true;try{const canvas=await renderNow()||lastCanvas;if(!canvas)throw new Error("Сначала загрузите изображение");if(format==="heic"){const encoder=window.safelightHeicCodec?.encodeCanvas;if(typeof encoder!=="function")throw new Error("Локальный HEIC WASM-кодек не загрузился");download(await encoder(canvas),baseName()+"-safelight.heic")}else if(format==="pdf"){if(!window.jspdf?.jsPDF)throw new Error("Локальный PDF-модуль не загрузился");const {jsPDF}=window.jspdf,orientation=canvas.width>canvas.height?"landscape":"portrait",doc=new jsPDF({orientation,unit:"mm",format:"a4"}),pageW=doc.internal.pageSize.getWidth(),pageH=doc.internal.pageSize.getHeight(),margin=10,scale=Math.min((pageW-margin*2)/canvas.width,(pageH-margin*2)/canvas.height),w=canvas.width*scale,h=canvas.height*scale,jpeg=canvas.toDataURL("image/jpeg",.94);doc.addImage(jpeg,"JPEG",(pageW-w)/2,(pageH-h)/2,w,h,undefined,"FAST");download(doc.output("blob"),baseName()+"-safelight.pdf")}else{let output=canvas;if(format==="jpeg"){output=document.createElement("canvas");output.width=canvas.width;output.height=canvas.height;const ctx=output.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,output.width,output.height);ctx.drawImage(canvas,0,0)}const types={png:"image/png",jpeg:"image/jpeg",webp:"image/webp"},blob=await canvasBlob(output,types[format]||"image/png",format==="png"?undefined:.92);download(blob,baseName()+"-safelight."+(format==="jpeg"?"jpg":format))}hint("Экспорт коррекции готов.")}catch(error){console.error("Safelight advanced adjust export:",error);hint(error.message||"Не удалось экспортировать результат")}finally{exporting=false}}
  function patchExportMenu(){if(!active())return;const menu=document.querySelector(".sl-export-menu");if(!menu)return;menu.innerHTML='<div class="sl-export-menu-title">Экспорт коррекции</div><button class="sl-export-option" type="button" data-export="webp"><span>WebP</span><span>оптимально</span></button><button class="sl-export-option" type="button" data-export="jpeg"><span>JPEG</span><span>совместимо</span></button><button class="sl-export-option" type="button" data-export="png"><span>PNG</span><span>без потерь</span></button><button class="sl-export-option" type="button" data-export="heic"><span>HEIC</span><span>HEVC</span></button><button class="sl-export-option" type="button" data-export="pdf"><span>PDF</span><span>документ</span></button><div class="sl-export-sep"></div><div class="sl-export-menu-note">Экспортируется текущая расширенная коррекция. Оригинал не изменяется.</div>'}
  function installExportOverride(){document.addEventListener("click",event=>{if(event.target.closest("#sl-export")&&active())setTimeout(patchExportMenu,0)},true);document.addEventListener("click",event=>{const option=event.target.closest(".sl-export-option[data-export]");if(!option||!active())return;const format=option.dataset.export;if(!["webp","jpeg","png","heic","pdf"].includes(format))return;event.preventDefault();event.stopImmediatePropagation();option.closest(".sl-export-wrap")?.classList.remove("open");exportAdjusted(format)},true)}

  function boot(){const panel=$("panel-adjust"),preview=$("previewImg"),app=document.querySelector(".sl-app");if(!panel||!preview||!app){setTimeout(boot,50);return}installPanel();installExportOverride();new MutationObserver(()=>{sourceImage=null;sourceSrc="";lastCanvas=null;if(active())scheduleRender(0)}).observe(preview,{attributes:true,attributeFilter:["src"]});window.addEventListener("safelight:toolchange",()=>setTimeout(()=>{updateInspector();if(active())scheduleRender(0)},20));window.addEventListener("safelight:live-render",event=>{if(event.detail?.tool==="adjust")scheduleRender(0)});updateInspector();if(active())scheduleRender(0)}
  window.safelightAdvancedAdjust=Object.freeze({render:renderNow,state,applyPreset});boot();
})();
