(function(){
"use strict";
let originalFile=null,originalSize=0,originalType="";
const sourceCanvas=document.createElement("canvas"),sourceCtx=sourceCanvas.getContext("2d");
let imgW=0,imgH=0,compressedBlob=null,compressedExt="",convertedBlob=null,convertedExt="";
let statOps=0,statSavedBytes=0,statTiles=0;
function formatBytes(bytes){if(bytes<1024)return bytes+" B";if(bytes<1024*1024)return(bytes/1024).toFixed(1)+" KB";return(bytes/(1024*1024)).toFixed(2)+" MB"}
function mimeFor(fmt){return fmt==="png"?"image/png":fmt==="webp"?"image/webp":"image/jpeg"}
function extFor(fmt){return fmt==="png"?"png":fmt==="webp"?"webp":"jpg"}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
function baseName(name){const i=name.lastIndexOf(".");return i>0?name.slice(0,i):name}
function bumpStats(){document.getElementById("stat-ops").textContent=String(statOps);document.getElementById("stat-saved").textContent=statSavedBytes>0?formatBytes(statSavedBytes):"0 KB";document.getElementById("stat-tiles").textContent=String(statTiles)}
const dropzone=document.getElementById("dropzone"),fileInput=document.getElementById("fileInput"),filemeta=document.getElementById("filemeta"),stageEmpty=document.getElementById("stageEmpty"),previewWrap=document.getElementById("previewWrap"),previewImg=document.getElementById("previewImg"),gridOverlay=document.getElementById("gridOverlay"),readout=document.getElementById("readout"),tabBtns=document.querySelectorAll(".tab-btn"),panels={compress:document.getElementById("panel-compress"),slice:document.getElementById("panel-slice"),convert:document.getElementById("panel-convert")};
document.getElementById("hero-cta").addEventListener("click",()=>{document.getElementById("workspace").scrollIntoView({behavior:"smooth"});dropzone.click()});
document.querySelectorAll(".tool-card").forEach(card=>card.addEventListener("click",()=>{const tab=card.dataset.tab;document.getElementById("workspace").scrollIntoView({behavior:"smooth"});const btn=document.querySelector('.tab-btn[data-tab="'+tab+'"]');if(btn&&!btn.disabled)btn.click()}));
["dragover","dragenter"].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.classList.add("drag")}));
["dragleave","drop"].forEach(ev=>dropzone.addEventListener(ev,e=>{e.preventDefault();dropzone.classList.remove("drag")}));
dropzone.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(f)handleFile(f)});dropzone.addEventListener("click",()=>fileInput.click());fileInput.addEventListener("change",e=>{if(e.target.files[0])handleFile(e.target.files[0])});
function handleFile(file){if(!file.type.startsWith("image/")){alert("Пожалуйста, выберите файл изображения.");return}originalFile=file;originalSize=file.size;originalType=file.type;const url=URL.createObjectURL(file),img=new Image();img.onload=function(){imgW=img.naturalWidth;imgH=img.naturalHeight;sourceCanvas.width=imgW;sourceCanvas.height=imgH;sourceCtx.imageSmoothingEnabled=true;sourceCtx.imageSmoothingQuality="high";sourceCtx.clearRect(0,0,imgW,imgH);sourceCtx.drawImage(img,0,0,imgW,imgH);previewImg.src=url;stageEmpty.style.display="none";previewWrap.style.display="inline-block";readout.style.display="flex";document.getElementById("meta-name").textContent=file.name;document.getElementById("meta-size").textContent=formatBytes(file.size);document.getElementById("meta-type").textContent=file.type||"—";document.getElementById("meta-dims").textContent=imgW+" × "+imgH;filemeta.classList.add("show");document.getElementById("ro-dims").textContent=imgW+" × "+imgH+" px";document.getElementById("ro-size").textContent=formatBytes(file.size);document.getElementById("ro-format").textContent=file.type.replace("image/","").toUpperCase();document.getElementById("t-name").textContent=file.name;document.getElementById("t-name2").textContent=file.name;document.getElementById("t-status").textContent="готово — открыто в мастерской";document.getElementById("t-dims").textContent=imgW+"x"+imgH+" px, "+(file.type.replace("image/","")||"—").toUpperCase();document.getElementById("t-size").textContent=formatBytes(file.size);tabBtns.forEach(b=>b.disabled=false);["c-result","v-result"].forEach(id=>document.getElementById(id).classList.remove("show"));document.getElementById("c-status").textContent="";document.getElementById("v-status").textContent="";document.getElementById("s-status").textContent="";document.querySelectorAll(".af").forEach(el=>el.classList.remove("show"));requestAnimationFrame(()=>setTimeout(()=>document.querySelectorAll(".af").forEach(el=>el.classList.add("show")),60));renderGridOverlay()};img.src=url}
tabBtns.forEach(btn=>btn.addEventListener("click",()=>{if(btn.disabled)return;tabBtns.forEach(b=>b.classList.remove("active"));btn.classList.add("active");Object.values(panels).forEach(p=>p.classList.remove("active"));panels[btn.dataset.tab].classList.add("active");gridOverlay.style.display=btn.dataset.tab==="slice"?"block":"none";if(btn.dataset.tab==="slice")renderGridOverlay()}));gridOverlay.style.display="none";
const cFormat=document.getElementById("c-format"),cQuality=document.getElementById("c-quality"),cQualityVal=document.getElementById("c-quality-val"),cRun=document.getElementById("c-run"),cResult=document.getElementById("c-result"),cStatus=document.getElementById("c-status");
function syncQualityDisabled(){cQuality.disabled=cFormat.value==="png"}cFormat.addEventListener("change",syncQualityDisabled);syncQualityDisabled();cQuality.addEventListener("input",()=>cQualityVal.textContent=cQuality.value+"%");
cRun.addEventListener("click",()=>{if(!originalFile)return;cRun.disabled=true;cStatus.textContent="Сжимаю…";const fmt=cFormat.value,q=Number(cQuality.value)/100;setTimeout(()=>{sourceCanvas.toBlob(blob=>{cRun.disabled=false;if(!blob){cStatus.textContent="Не удалось сжать изображение.";return}compressedBlob=blob;compressedExt=extFor(fmt);const before=originalSize,after=blob.size,diff=before-after,pct=before>0?Math.round(diff/before*100):0;document.getElementById("c-before").textContent=formatBytes(before);document.getElementById("c-after").textContent=formatBytes(after);const sEl=document.getElementById("c-savings");if(diff>=0){sEl.textContent="−"+pct+"%";sEl.classList.remove("negative");statSavedBytes+=diff}else{sEl.textContent="+"+Math.abs(pct)+"%";sEl.classList.add("negative")}cResult.classList.add("show");cStatus.textContent="Готово.";statOps++;bumpStats()},mimeFor(fmt),fmt==="png"?undefined:q)},30)});
document.getElementById("c-download").addEventListener("click",()=>{if(compressedBlob&&originalFile)downloadBlob(compressedBlob,baseName(originalFile.name)+"-compressed."+compressedExt)});
const sModeWrap=document.getElementById("s-mode"),sRowsField=document.getElementById("s-rows-field"),sColsField=document.getElementById("s-cols-field"),sRows=document.getElementById("s-rows"),sCols=document.getElementById("s-cols"),sFormat=document.getElementById("s-format"),sQualityRow=document.getElementById("s-quality-row"),sQuality=document.getElementById("s-quality"),sQualityVal=document.getElementById("s-quality-val"),sRun=document.getElementById("s-run"),sStatus=document.getElementById("s-status");let sliceMode="grid";
sModeWrap.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{sModeWrap.querySelectorAll("button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");sliceMode=btn.dataset.mode;sRowsField.style.display=sliceMode==="vertical"?"none":"flex";sColsField.style.display=sliceMode==="horizontal"?"none":"flex";renderGridOverlay()}));[sRows,sCols].forEach(inp=>inp.addEventListener("input",renderGridOverlay));sFormat.addEventListener("change",()=>{sQualityRow.style.display=sFormat.value==="png"?"none":"flex"});sQuality.addEventListener("input",()=>sQualityVal.textContent=sQuality.value+"%");
function currentGrid(){let rows=Math.max(1,Math.min(20,Number(sRows.value)||1)),cols=Math.max(1,Math.min(20,Number(sCols.value)||1));if(sliceMode==="horizontal")cols=1;if(sliceMode==="vertical")rows=1;return{rows,cols}}
function renderGridOverlay(){gridOverlay.innerHTML="";if(!imgW)return;const{rows,cols}=currentGrid();for(let c=1;c<cols;c++){const line=document.createElement("div");line.className="grid-line v";line.style.left=c/cols*100+"%";gridOverlay.appendChild(line)}for(let r=1;r<rows;r++){const line=document.createElement("div");line.className="grid-line h";line.style.top=r/rows*100+"%";gridOverlay.appendChild(line)}}
function boundaries(total,n){const arr=[0],step=Math.floor(total/n);for(let i=1;i<n;i++)arr.push(i*step);arr.push(total);return arr}
sRun.addEventListener("click",async()=>{if(!originalFile||typeof JSZip==="undefined"){sStatus.textContent="Библиотека ZIP не загрузилась. Проверьте соединение.";return}sRun.disabled=true;const{rows,cols}=currentGrid(),fmt=sFormat.value,q=Number(sQuality.value)/100,mime=mimeFor(fmt),ext=extFor(fmt);sStatus.textContent="Нарезаю "+rows+"×"+cols+" ("+rows*cols+" фрагментов)…";const xs=boundaries(imgW,cols),ys=boundaries(imgH,rows),zip=new JSZip(),tileCanvas=document.createElement("canvas"),tileCtx=tileCanvas.getContext("2d");let count=0;for(let r=0;r<rows;r++){for(let c=0;c<cols;c++){const x0=xs[c],x1=xs[c+1],y0=ys[r],y1=ys[r+1],w=x1-x0,h=y1-y0;tileCanvas.width=w;tileCanvas.height=h;tileCtx.clearRect(0,0,w,h);tileCtx.drawImage(sourceCanvas,x0,y0,w,h,0,0,w,h);const blob=await new Promise(res=>tileCanvas.toBlob(res,mime,fmt==="png"?undefined:q));zip.file("tile_r"+(r+1)+"_c"+(c+1)+"."+ext,blob);count++;sStatus.textContent="Обработано "+count+" / "+rows*cols+"…"}}sStatus.textContent="Собираю ZIP-архив…";const zipBlob=await zip.generateAsync({type:"blob"});downloadBlob(zipBlob,baseName(originalFile.name)+"-slices.zip");sStatus.textContent="Готово — "+rows*cols+" фрагментов в архиве.";sRun.disabled=false;statTiles+=rows*cols;statOps++;bumpStats()});
const vFormat=document.getElementById("v-format"),vQualityRow=document.getElementById("v-quality-row"),vQuality=document.getElementById("v-quality"),vQualityVal=document.getElementById("v-quality-val"),vRun=document.getElementById("v-run"),vResult=document.getElementById("v-result"),vStatus=document.getElementById("v-status");vFormat.addEventListener("change",()=>{vQualityRow.style.display=vFormat.value==="png"?"none":"flex"});vQuality.addEventListener("input",()=>vQualityVal.textContent=vQuality.value+"%");
vRun.addEventListener("click",()=>{if(!originalFile)return;vRun.disabled=true;vStatus.textContent="Конвертирую…";const fmt=vFormat.value,q=Number(vQuality.value)/100;setTimeout(()=>{sourceCanvas.toBlob(blob=>{vRun.disabled=false;if(!blob){vStatus.textContent="Не удалось конвертировать изображение.";return}convertedBlob=blob;convertedExt=extFor(fmt);document.getElementById("v-before").textContent=(originalType.replace("image/","").toUpperCase()||"—")+" · "+formatBytes(originalSize);document.getElementById("v-after").textContent=fmt.toUpperCase()+" · "+formatBytes(blob.size);vResult.classList.add("show");vStatus.textContent="Готово.";statOps++;bumpStats()},mimeFor(fmt),fmt==="png"?undefined:q)},30)});
document.getElementById("v-download").addEventListener("click",()=>{if(convertedBlob&&originalFile)downloadBlob(convertedBlob,baseName(originalFile.name)+"-converted."+convertedExt)});bumpStats();
})();
