(function(){
  'use strict';
  if(window.safelightCanvasToolsLoaded)return;
  window.safelightCanvasToolsLoaded=true;

  const $=id=>document.getElementById(id);
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const PREVIEW_MAX_SIDE=1800,PREVIEW_MAX_PIXELS=2200000;
  let sourceImage=null;
  let sourceSrc='';
  let renderTimer=0;
  let renderToken=0;
  let exportBusy=false;
  let interaction=null;

  function active(){return !!document.querySelector('#panel-canvas.active')}
  function previewScale(width,height){return Math.min(1,PREVIEW_MAX_SIDE/Math.max(1,width,height),Math.sqrt(PREVIEW_MAX_PIXELS/Math.max(1,width*height)))}
  function number(id,fallback){const value=Number($(id)?.value);return Number.isFinite(value)?value:fallback}
  function currentState(){return{
    preset:$('cv-preset')?.value||'original',width:clamp(Math.round(number('cv-width',sourceImage?.naturalWidth||1)),1,12000),height:clamp(Math.round(number('cv-height',sourceImage?.naturalHeight||1)),1,12000),fit:$('cv-fit')?.value||'contain',positionX:clamp(number('cv-pos-x',0),-100,100),positionY:clamp(number('cv-pos-y',0),-100,100),top:clamp(Math.round(number('cv-top',0)),0,6000),right:clamp(Math.round(number('cv-right',0)),0,6000),bottom:clamp(Math.round(number('cv-bottom',0)),0,6000),left:clamp(Math.round(number('cv-left',0)),0,6000),linked:!!$('cv-link-margins')?.checked,background:$('cv-bg-mode')?.value||'transparent',backgroundColor:$('cv-bg-color')?.value||'#ffffff',border:clamp(Math.round(number('cv-border',0)),0,200),borderColor:$('cv-border-color')?.value||'#ffffff',radius:clamp(Math.round(number('cv-radius',0)),0,1000),shadow:clamp(Math.round(number('cv-shadow',0)),0,100),quality:clamp(number('cv-quality',92),1,100)/100
  }}

  function panelMarkup(){return `<div class="panel-card sl-canvas-panel">
    <h2>ХОЛСТ / РАМКИ / ПОЛЯ</h2><p class="desc">Добавляйте пространство вокруг изображения, меняйте пропорции холста, фон и рамку без растягивания оригинала.</p>
    <div class="sl-canvas-section"><div class="sl-canvas-section-head"><span>Холст</span><small>готовые пропорции или точный размер</small></div>
      <div class="field"><label>Пропорции</label><select id="cv-preset"><option value="original" selected>Как у исходника</option><option value="1:1">1:1 · квадрат</option><option value="4:3">4:3</option><option value="3:2">3:2</option><option value="16:9">16:9</option><option value="9:16">9:16 · вертикально</option><option value="custom">Свой размер</option></select></div>
      <div class="field-row sl-canvas-size-row"><div class="field"><label>Ширина</label><input id="cv-width" type="number" min="1" max="12000" placeholder="—"></div><div class="field"><label>Высота</label><input id="cv-height" type="number" min="1" max="12000" placeholder="—"></div></div>
      <div class="field"><label>Изображение</label><select id="cv-fit"><option value="contain" selected>Вписать целиком</option><option value="original">Без масштабирования</option><option value="cover">Заполнить область</option></select></div>
      <div class="sl-canvas-position-control"><div class="sl-canvas-mini-head"><span>Положение изображения</span><small>перетащите точку</small></div><div class="sl-canvas-position-pad" id="cv-position-pad" role="application" aria-label="Позиционирование изображения"><div class="sl-canvas-position-axis x"></div><div class="sl-canvas-position-axis y"></div><button type="button" class="sl-canvas-position-knob" id="cv-position-knob" tabindex="-1" aria-hidden="true"></button></div><div class="sl-canvas-position-readout"><span>X <b id="cv-pos-x-val">0</b></span><span>Y <b id="cv-pos-y-val">0</b></span><button type="button" class="btn ghost" data-cv-center>Центр</button></div><input id="cv-pos-x" type="hidden" value="0"><input id="cv-pos-y" type="hidden" value="0"></div>
    </div>
    <div class="sl-canvas-section"><div class="sl-canvas-section-head"><span>Поля</span><small>тяните ручки вокруг изображения</small></div><label class="check-row sl-canvas-link"><input type="checkbox" id="cv-link-margins" checked> Связать четыре стороны</label>
      <input id="cv-top" type="hidden" value="0"><input id="cv-right" type="hidden" value="0"><input id="cv-bottom" type="hidden" value="0"><input id="cv-left" type="hidden" value="0">
      <div class="sl-canvas-margin-controller"><div class="sl-canvas-box" id="cv-margin-controller"><span class="sl-canvas-box-caption">ХОЛСТ</span><div class="sl-canvas-box-image" id="cv-margin-inner"><span>ИЗОБРАЖЕНИЕ</span><button type="button" class="sl-canvas-margin-handle top" data-cv-side="top" aria-label="Изменить верхнее поле"></button><button type="button" class="sl-canvas-margin-handle right" data-cv-side="right" aria-label="Изменить правое поле"></button><button type="button" class="sl-canvas-margin-handle bottom" data-cv-side="bottom" aria-label="Изменить нижнее поле"></button><button type="button" class="sl-canvas-margin-handle left" data-cv-side="left" aria-label="Изменить левое поле"></button></div></div><div class="sl-canvas-margin-readout"><span>↑ <b id="cv-top-val">0</b></span><span>→ <b id="cv-right-val">0</b></span><span>↓ <b id="cv-bottom-val">0</b></span><span>← <b id="cv-left-val">0</b></span></div></div>
      <label class="sl-canvas-linked-value"><span>Общее поле</span><span class="sl-canvas-compact-number"><input id="cv-margin-value" type="number" min="0" max="6000" value="0"><i>px</i></span></label><div class="sl-canvas-quick-margins"><button class="btn ghost" type="button" data-cv-margin="0">0</button><button class="btn ghost" type="button" data-cv-margin="16">16</button><button class="btn ghost" type="button" data-cv-margin="32">32</button><button class="btn ghost" type="button" data-cv-margin="64">64</button></div>
    </div>
    <div class="sl-canvas-section"><div class="sl-canvas-section-head"><span>Фон и рамка</span><small>прозрачность сохраняется в PNG/WebP/HEIC</small></div><div class="field-row sl-canvas-color-row"><div class="field"><label>Фон</label><select id="cv-bg-mode"><option value="transparent" selected>Прозрачный</option><option value="color">Цвет</option></select></div><div class="field sl-canvas-bg-color"><label>Цвет фона</label><input id="cv-bg-color" type="color" value="#ffffff"></div></div><div class="field-row sl-canvas-frame-row"><div class="field"><label>Рамка, px</label><input id="cv-border" type="number" min="0" max="200" value="0"></div><div class="field"><label>Цвет рамки</label><input id="cv-border-color" type="color" value="#ffffff"></div></div><div class="slider-row"><div class="top"><span>Скругление</span><b id="cv-radius-val">0 px</b></div><input id="cv-radius" type="range" min="0" max="300" value="0"></div><div class="slider-row"><div class="top"><span>Тень</span><b id="cv-shadow-val">0%</b></div><input id="cv-shadow" type="range" min="0" max="100" value="0"></div><div class="slider-row"><div class="top"><span>Качество JPEG/WebP</span><b id="cv-quality-val">92%</b></div><input id="cv-quality" type="range" min="1" max="100" value="92"></div></div>
    <div class="sl-canvas-note">Холст меняет итоговый размер файла, но исходное изображение остаётся нетронутым.</div></div>`}

  function createPanel(){if($('panel-canvas'))return $('panel-canvas');const panel=document.createElement('section');panel.className='panel';panel.id='panel-canvas';panel.innerHTML=panelMarkup();const host=$('sl-inspector-panels')||document.querySelector('main.workmain');host?.appendChild(panel);bindPanel(panel);bindVisualControls(panel);return panel}
  function createSidebarButton(){if(document.querySelector('.sl-sidebar [data-page="canvas"]'))return;const groups=[...document.querySelectorAll('.sl-sidebar .sl-nav-group')],group=groups.find(item=>item.querySelector('.sl-nav-label')?.textContent.trim()==='Редактирование')||groups[0];if(!group)return;const button=document.createElement('button');button.type='button';button.className='top-nav-link sl-tool';button.dataset.page='canvas';button.innerHTML='<span class="nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM8 9h8v6H8zM8 3v4M16 3v4M8 17v4M16 17v4M2 9h4M18 9h4M2 15h4M18 15h4"/></svg></span><span>Холст</span>';button.addEventListener('click',event=>{event.preventDefault();activateCanvas()});group.appendChild(button)}
  function activateCanvas(){document.body.classList.remove('page-home','sl-palette-active','sl-privacy-active');document.body.classList.add('page-tool');document.querySelectorAll('.panel').forEach(panel=>panel.classList.remove('active'));createPanel().classList.add('active');document.querySelectorAll('.sl-sidebar .sl-tool').forEach(button=>button.classList.toggle('active',button.dataset.page==='canvas'));const title=$('sl-inspector-title'),desc=$('sl-inspector-desc');if(title)title.textContent='Холст / рамки / поля';if(desc)desc.textContent='Пропорции, визуальные поля, фон, рамка и свободное позиционирование изображения.';window.dispatchEvent(new CustomEvent('safelight:toolchange',{detail:{page:'canvas'}}));syncSource().then(()=>{ensureDimensions(false);scheduleRender(0)}).catch(()=>{})}

  function syncSource(){const preview=$('previewImg'),src=preview?.src||'';if(!src){sourceImage=null;sourceSrc='';return Promise.resolve(null)}if(sourceImage&&sourceSrc===src)return Promise.resolve(sourceImage);return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{sourceImage=image;sourceSrc=src;ensureDimensions(true);resolve(image)};image.onerror=()=>reject(new Error('Не удалось открыть изображение'));image.src=src})}
  function ratioForPreset(preset){const map={'1:1':1,'4:3':4/3,'3:2':3/2,'16:9':16/9,'9:16':9/16};return map[preset]||null}
  function sizeForRatio(ratio){const sw=sourceImage?.naturalWidth||number('cv-width',1),sh=sourceImage?.naturalHeight||number('cv-height',1),sourceRatio=sw/sh;if(sourceRatio>=ratio)return{width:sw,height:Math.max(1,Math.round(sw/ratio))};return{width:Math.max(1,Math.round(sh*ratio)),height:sh}}
  function ensureDimensions(force){if(!sourceImage)return;const preset=$('cv-preset')?.value||'original';let size=null;if(preset==='original')size={width:sourceImage.naturalWidth,height:sourceImage.naturalHeight};else if(ratioForPreset(preset))size=sizeForRatio(ratioForPreset(preset));else if(force&&(!$('cv-width')?.value||!$('cv-height')?.value))size={width:sourceImage.naturalWidth,height:sourceImage.naturalHeight};if(size){if($('cv-width'))$('cv-width').value=size.width;if($('cv-height'))$('cv-height').value=size.height}normalizeMargins();updateControlState()}

  function marginIds(){return['cv-top','cv-right','cv-bottom','cv-left']}
  function linkedMax(){const s=currentState();return Math.max(0,Math.min(6000,Math.floor((Math.min(s.width,s.height)-1)/2)))}
  function sideMax(side){const s=currentState();if(side==='top')return Math.max(0,Math.min(6000,s.height-s.bottom-1));if(side==='bottom')return Math.max(0,Math.min(6000,s.height-s.top-1));if(side==='left')return Math.max(0,Math.min(6000,s.width-s.right-1));return Math.max(0,Math.min(6000,s.width-s.left-1))}
  function writeMargin(id,value){if($(id))$(id).value=String(Math.max(0,Math.round(value)))}
  function setAllMargins(value){const v=clamp(Math.round(value),0,linkedMax());marginIds().forEach(id=>writeMargin(id,v));if($('cv-margin-value'))$('cv-margin-value').value=String(v);updateControlState();scheduleRender()}
  function setMargin(side,value){if($('cv-link-margins')?.checked){setAllMargins(value);return}writeMargin('cv-'+side,clamp(Math.round(value),0,sideMax(side)));updateControlState();scheduleRender()}
  function normalizeMargins(){
    if($('cv-link-margins')?.checked){const v=clamp(Math.round(number('cv-top',0)),0,linkedMax());marginIds().forEach(id=>writeMargin(id,v));if($('cv-margin-value'))$('cv-margin-value').value=String(v);return}
    ['top','right','bottom','left'].forEach(side=>writeMargin('cv-'+side,clamp(Math.round(number('cv-'+side,0)),0,sideMax(side))));
  }

  function updateControlState(){
    const custom=$('cv-preset')?.value==='custom';document.querySelector('.sl-canvas-size-row')?.classList.toggle('sl-canvas-custom-size',custom);if($('cv-width'))$('cv-width').disabled=!custom;if($('cv-height'))$('cv-height').disabled=!custom;document.querySelector('.sl-canvas-bg-color')?.classList.toggle('active',$('cv-bg-mode')?.value==='color');const panel=$('panel-canvas');panel?.classList.toggle('sl-canvas-unlinked',!$('cv-link-margins')?.checked);if($('cv-radius-val'))$('cv-radius-val').textContent=`${Math.round(number('cv-radius',0))} px`;if($('cv-shadow-val'))$('cv-shadow-val').textContent=`${Math.round(number('cv-shadow',0))}%`;if($('cv-quality-val'))$('cv-quality-val').textContent=`${Math.round(number('cv-quality',92))}%`;
    const s=currentState(),inner=$('cv-margin-inner');if(inner){inner.style.top=Math.min(42,s.top/Math.max(1,s.height)*100)+'%';inner.style.right=Math.min(42,s.right/Math.max(1,s.width)*100)+'%';inner.style.bottom=Math.min(42,s.bottom/Math.max(1,s.height)*100)+'%';inner.style.left=Math.min(42,s.left/Math.max(1,s.width)*100)+'%'}
    [['cv-top-val',s.top],['cv-right-val',s.right],['cv-bottom-val',s.bottom],['cv-left-val',s.left]].forEach(([id,value])=>{if($(id))$(id).textContent=value+' px'});if($('cv-margin-value')&&s.linked)$('cv-margin-value').value=String(s.top);const knob=$('cv-position-knob');if(knob){knob.style.left=((s.positionX+100)/2)+'%';knob.style.top=((s.positionY+100)/2)+'%'}if($('cv-pos-x-val'))$('cv-pos-x-val').textContent=(s.positionX>0?'+':'')+Math.round(s.positionX);if($('cv-pos-y-val'))$('cv-pos-y-val').textContent=(s.positionY>0?'+':'')+Math.round(s.positionY)
  }

  function setPosition(x,y){if($('cv-pos-x'))$('cv-pos-x').value=String(clamp(Math.round(x),-100,100));if($('cv-pos-y'))$('cv-pos-y').value=String(clamp(Math.round(y),-100,100));updateControlState();scheduleRender()}
  function positionFromPointer(event){const pad=$('cv-position-pad');if(!pad)return;const rect=pad.getBoundingClientRect(),x=((event.clientX-rect.left)/Math.max(1,rect.width))*200-100,y=((event.clientY-rect.top)/Math.max(1,rect.height))*200-100;setPosition(x,y)}
  function bindVisualControls(panel){const pad=panel.querySelector('#cv-position-pad');if(pad)pad.addEventListener('pointerdown',event=>{event.preventDefault();interaction={type:'position',pointerId:event.pointerId};pad.setPointerCapture?.(event.pointerId);positionFromPointer(event)});panel.querySelectorAll('[data-cv-side]').forEach(handle=>handle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();const side=handle.dataset.cvSide,box=$('cv-margin-controller')?.getBoundingClientRect();if(!box)return;interaction={type:'margin',pointerId:event.pointerId,side,startX:event.clientX,startY:event.clientY,startValue:number('cv-'+side,0),box};handle.setPointerCapture?.(event.pointerId);document.body.classList.add('sl-canvas-dragging')}))}
  function onPointerMove(event){if(!interaction||event.pointerId!==interaction.pointerId)return;if(interaction.type==='position'){positionFromPointer(event);return}const s=currentState(),side=interaction.side,horizontal=side==='left'||side==='right',dimension=horizontal?s.width:s.height,visual=horizontal?interaction.box.width:interaction.box.height;let delta=horizontal?event.clientX-interaction.startX:event.clientY-interaction.startY;if(side==='right'||side==='bottom')delta=-delta;setMargin(side,interaction.startValue+delta*(dimension/Math.max(1,visual)))}
  function endPointer(event){if(!interaction||event.pointerId!==interaction.pointerId)return;interaction=null;document.body.classList.remove('sl-canvas-dragging');scheduleRender(0)}
  window.addEventListener('pointermove',onPointerMove,{passive:false});window.addEventListener('pointerup',endPointer);window.addEventListener('pointercancel',endPointer);

  function bindPanel(panel){panel.addEventListener('input',event=>{if(event.target.id==='cv-margin-value'&&$('cv-link-margins')?.checked){setAllMargins(number('cv-margin-value',0));return}updateControlState();scheduleRender()},true);panel.addEventListener('change',event=>{if(event.target.id==='cv-preset')ensureDimensions(false);if(event.target.id==='cv-link-margins'&&event.target.checked)setAllMargins(number('cv-top',0));updateControlState();scheduleRender(0)},true);panel.addEventListener('click',event=>{const quick=event.target.closest('[data-cv-margin]');if(quick){setAllMargins(Number(quick.dataset.cvMargin)||0);return}if(event.target.closest('[data-cv-center]')){setPosition(0,0);scheduleRender(0)}})}

  function roundRect(ctx,x,y,w,h,r){r=Math.max(0,Math.min(r,w/2,h/2));ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
  function alignedPosition(xValue,yValue,areaX,areaY,areaW,areaH,w,h){const fx=(clamp(xValue,-100,100)+100)/200,fy=(clamp(yValue,-100,100)+100)/200;return{x:areaX+(areaW-w)*fx,y:areaY+(areaH-h)*fy}}
  async function buildCanvas(options){
    const image=await syncSource();if(!image)return null;normalizeMargins();
    const full=currentState(),factor=options?.preview?previewScale(full.width,full.height):1;
    const s={...full,width:Math.max(1,Math.round(full.width*factor)),height:Math.max(1,Math.round(full.height*factor)),top:full.top*factor,right:full.right*factor,bottom:full.bottom*factor,left:full.left*factor,border:full.border*factor,radius:full.radius*factor};
    const out=document.createElement('canvas');out.width=s.width;out.height=s.height;const ctx=out.getContext('2d');ctx.clearRect(0,0,out.width,out.height);
    if(s.background==='color'){ctx.fillStyle=s.backgroundColor;ctx.fillRect(0,0,out.width,out.height)}
    const areaX=Math.min(s.left,out.width-1),areaY=Math.min(s.top,out.height-1),areaW=Math.max(1,out.width-s.left-s.right),areaH=Math.max(1,out.height-s.top-s.bottom);let scale=1;
    if(s.fit==='contain')scale=Math.min(areaW/image.naturalWidth,areaH/image.naturalHeight);else if(s.fit==='cover')scale=Math.max(areaW/image.naturalWidth,areaH/image.naturalHeight);
    const drawW=Math.max(1,image.naturalWidth*scale),drawH=Math.max(1,image.naturalHeight*scale),pos=alignedPosition(s.positionX,s.positionY,areaX,areaY,areaW,areaH,drawW,drawH),frame=s.fit==='cover'?{x:areaX,y:areaY,w:areaW,h:areaH}:{x:pos.x,y:pos.y,w:drawW,h:drawH};
    if(full.shadow>0){ctx.save();ctx.shadowColor=`rgba(0,0,0,${0.12+full.shadow/100*.48})`;ctx.shadowBlur=Math.max(.5,(2+full.shadow*.32)*factor);ctx.shadowOffsetY=Math.max(.25,(1+full.shadow*.09)*factor);ctx.fillStyle='rgba(0,0,0,.01)';roundRect(ctx,frame.x,frame.y,frame.w,frame.h,s.radius);ctx.fill();ctx.restore()}
    ctx.save();if(s.fit==='cover'){roundRect(ctx,areaX,areaY,areaW,areaH,s.radius);ctx.clip()}else{roundRect(ctx,frame.x,frame.y,frame.w,frame.h,s.radius);ctx.clip()}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(image,pos.x,pos.y,drawW,drawH);ctx.restore();
    if(s.border>0){ctx.save();ctx.strokeStyle=s.borderColor;ctx.lineWidth=s.border;roundRect(ctx,frame.x+s.border/2,frame.y+s.border/2,Math.max(1,frame.w-s.border),Math.max(1,frame.h-s.border),Math.max(0,s.radius-s.border/2));ctx.stroke();ctx.restore()}return out
  }
  async function renderNow(){if(!active())return null;const token=++renderToken;try{const built=await buildCanvas({preview:true});if(!built||token!==renderToken||!active())return null;let live=$('sl-live-canvas');if(!live){const wrap=$('previewWrap');live=document.createElement('canvas');live.id='sl-live-canvas';live.className='sl-live-canvas';wrap?.appendChild(live)}live.width=built.width;live.height=built.height;const ctx=live.getContext('2d');ctx.clearRect(0,0,live.width,live.height);ctx.drawImage(built,0,0);$('previewWrap')?.classList.add('sl-live-ready');const full=currentState();if($('ro-dims'))$('ro-dims').textContent=`${full.width} × ${full.height} px`;if($('ro-format'))$('ro-format').textContent='CANVAS';return built}catch(error){console.error('Safelight canvas:',error);hint(error.message||'Не удалось построить холст');return null}}
  function scheduleRender(delay){clearTimeout(renderTimer);renderTimer=setTimeout(renderNow,delay==null?70:delay)}

  function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Не удалось подготовить файл')),type,quality))}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
  function baseName(){return (($('meta-name')?.textContent||'safelight').trim().replace(/\.[^.]+$/,'')||'safelight')}
  function hint(text){const el=$('sl-export-hint');if(!el)return;el.textContent=text;el.classList.add('show');clearTimeout(hint.timer);hint.timer=setTimeout(()=>el.classList.remove('show'),3000)}
  async function exportCanvas(format){if(exportBusy)return;exportBusy=true;try{const canvas=await buildCanvas({preview:false});if(!canvas)throw new Error('Сначала загрузите изображение');const s=currentState();if(format==='heic'){const encoder=window.safelightHeicCodec?.encodeCanvas;if(typeof encoder!=='function')throw new Error('Локальный HEIC WASM-кодек не загрузился');download(await encoder(canvas),baseName()+'-canvas.heic');return}if(format==='pdf'){if(!window.jspdf?.jsPDF)throw new Error('Локальный PDF-модуль не загрузился');const {jsPDF}=window.jspdf,orientation=canvas.width>canvas.height?'landscape':'portrait',doc=new jsPDF({orientation,unit:'mm',format:'a4'}),pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),margin=10,scale=Math.min((pw-margin*2)/canvas.width,(ph-margin*2)/canvas.height),w=canvas.width*scale,h=canvas.height*scale;doc.addImage(canvas.toDataURL('image/png'),'PNG',(pw-w)/2,(ph-h)/2,w,h,undefined,'FAST');download(doc.output('blob'),baseName()+'-canvas.pdf');return}let target=canvas,type='image/png',ext='png',quality=undefined;if(format==='webp'){type='image/webp';ext='webp';quality=s.quality}else if(format==='jpeg'){type='image/jpeg';ext='jpg';quality=s.quality;const opaque=document.createElement('canvas');opaque.width=canvas.width;opaque.height=canvas.height;const ctx=opaque.getContext('2d');ctx.fillStyle=s.background==='color'?s.backgroundColor:'#ffffff';ctx.fillRect(0,0,opaque.width,opaque.height);ctx.drawImage(canvas,0,0);target=opaque}download(await canvasBlob(target,type,quality),baseName()+'-canvas.'+ext)}finally{exportBusy=false}}
  function patchExportMenu(){if(!active())return;const menu=document.querySelector('.sl-export-menu');if(!menu)return;menu.innerHTML='<div class="sl-export-menu-title">Экспорт холста</div><button class="sl-export-option" type="button" data-export="png"><span>PNG</span><span>прозрачность</span></button><button class="sl-export-option" type="button" data-export="webp"><span>WebP</span><span>оптимально</span></button><button class="sl-export-option" type="button" data-export="jpeg"><span>JPEG</span><span>совместимо</span></button><button class="sl-export-option" type="button" data-export="heic"><span>HEIC</span><span>HEVC</span></button><button class="sl-export-option" type="button" data-export="pdf"><span>PDF</span><span>документ</span></button><div class="sl-export-sep"></div><div class="sl-export-menu-note">Экспортируется текущий холст со всеми полями, рамкой и фоном.</div>'}
  function bindExport(){document.addEventListener('click',event=>{if(event.target.closest('#sl-export')&&active())setTimeout(patchExportMenu,0)},true);document.addEventListener('click',event=>{const option=event.target.closest('.sl-export-option[data-export]');if(!option||!active())return;event.preventDefault();event.stopImmediatePropagation();document.querySelector('.sl-export-wrap')?.classList.remove('open');exportCanvas(option.dataset.export).then(()=>hint('Экспорт холста готов.')).catch(error=>{console.error(error);hint(error.message||'Не удалось экспортировать холст')})},true)}
  function install(){if(!document.querySelector('.sl-app')||!$('sl-inspector-panels')){setTimeout(install,60);return}createPanel();createSidebarButton();bindExport();updateControlState();const preview=$('previewImg');if(preview)new MutationObserver(()=>{sourceImage=null;sourceSrc='';syncSource().then(()=>{if(active())scheduleRender(0)}).catch(()=>{})}).observe(preview,{attributes:true,attributeFilter:['src']});window.addEventListener('safelight:toolchange',event=>{if(event.detail?.page!=='canvas'&&!active())return;if(active()){syncSource().then(()=>scheduleRender(0)).catch(()=>{})}})}

  window.safelightCanvasTools=Object.freeze({activate:activateCanvas,render:()=>buildCanvas({preview:false}),renderPreview:renderNow,export:exportCanvas,state:currentState});install();
})();
