(function(){
  'use strict';
  if(window.safelightMetadataToolsLoaded)return;
  window.safelightMetadataToolsLoaded=true;

  const $=id=>document.getElementById(id);
  const decoder=new TextDecoder('utf-8',{fatal:false});
  const encoder=new TextEncoder();
  const copyValues=new Map();
  let currentFile=null,currentSourceKind='none',report=null,analysisToken=0,previewToken=0,exportBusy=false;

  const TAGS={
    ifd0:{0x010e:'description',0x010f:'make',0x0110:'model',0x0112:'orientation',0x011a:'xResolution',0x011b:'yResolution',0x0128:'resolutionUnit',0x0131:'software',0x0132:'dateTime',0x013b:'artist',0x8298:'copyright'},
    exif:{0x829a:'exposureTime',0x829d:'fNumber',0x8822:'exposureProgram',0x8827:'iso',0x9003:'dateOriginal',0x9004:'dateDigitized',0x9201:'shutterSpeed',0x9202:'apertureValue',0x9204:'exposureBias',0x9207:'meteringMode',0x9208:'lightSource',0x9209:'flash',0x920a:'focalLength',0x9286:'userComment',0xa001:'colorSpace',0xa002:'pixelWidth',0xa003:'pixelHeight',0xa402:'exposureMode',0xa403:'whiteBalance',0xa404:'digitalZoom',0xa405:'focal35',0xa406:'sceneCapture',0xa407:'gainControl',0xa408:'contrast',0xa409:'saturationExif',0xa40a:'sharpnessExif',0xa420:'imageUniqueId',0xa430:'cameraOwner',0xa431:'bodySerial',0xa433:'lensMake',0xa434:'lensModel',0xa435:'lensSerial'}
  };
  const esc=value=>String(value==null?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
  function fmtBytes(n){n=Number(n)||0;if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(2)+' MB'}
  function fileNameFallback(){return($('meta-name')?.textContent||'image').trim()||'image'}
  function active(){return!!document.querySelector('#panel-metadata.active')}
  function starts(bytes,pos,text){if(pos<0||pos+text.length>bytes.length)return false;for(let i=0;i<text.length;i++)if(bytes[pos+i]!==text.charCodeAt(i))return false;return true}
  function safeGet(view,method,offset,little){try{if(offset<0||offset>=view.byteLength)return null;if(method==='getUint8')return view.getUint8(offset);if(method==='getInt8')return view.getInt8(offset);return view[method](offset,little)}catch(_){return null}}
  function typeSize(type){return({1:1,2:1,3:2,4:4,5:8,7:1,9:4,10:8})[type]||0}
  function readAscii(view,pos,count){if(pos==null||count<=0||pos+count>view.byteLength)return'';const bytes=new Uint8Array(view.buffer,view.byteOffset+pos,count);let end=bytes.indexOf(0);if(end<0)end=bytes.length;return decoder.decode(bytes.subarray(0,end)).trim()}
  function decodeUndefined(value){if(!Array.isArray(value)||!value.length)return'';const bytes=Uint8Array.from(value.filter(Number.isFinite).map(v=>v&255));if(!bytes.length)return'';let start=0;if(bytes.length>=8){const prefix=String.fromCharCode(...bytes.subarray(0,8)).replace(/\0/g,'').trim().toUpperCase();if(prefix.startsWith('ASCII')||prefix.startsWith('UNICODE')||prefix.startsWith('JIS'))start=8}return decoder.decode(bytes.subarray(start)).replace(/\0+$/g,'').trim()}
  function readTiffValue(view,base,entry,little,end){
    const type=safeGet(view,'getUint16',entry+2,little),count=safeGet(view,'getUint32',entry+4,little),size=typeSize(type);if(!type||count==null||!size||count>100000)return null;const total=size*count;let pos=entry+8;if(total>4){const rel=safeGet(view,'getUint32',entry+8,little);if(rel==null)return null;pos=base+rel}if(pos<base||pos+total>Math.min(view.byteLength,end))return null;
    const one=idx=>{const p=pos+idx*size;if(type===1||type===7)return safeGet(view,'getUint8',p);if(type===3)return safeGet(view,'getUint16',p,little);if(type===4)return safeGet(view,'getUint32',p,little);if(type===9)return safeGet(view,'getInt32',p,little);if(type===5||type===10){const signed=type===10,num=safeGet(view,signed?'getInt32':'getUint32',p,little),den=safeGet(view,signed?'getInt32':'getUint32',p+4,little);if(num==null||den==null||den===0)return null;return{num,den,value:num/den}}return null};
    if(type===2)return readAscii(view,pos,count);if(count===1)return one(0);const values=[];for(let i=0;i<Math.min(count,256);i++)values.push(one(i));return values;
  }
  function parseTiff(buffer,tiffOffset,maxLength){
    const view=new DataView(buffer),base=tiffOffset||0,end=Math.min(view.byteLength,base+(maxLength||view.byteLength-base));if(base+8>end)return{raw:{},tagCount:0,gps:null};const order=String.fromCharCode(view.getUint8(base),view.getUint8(base+1)),little=order==='II';if(!little&&order!=='MM')return{raw:{},tagCount:0,gps:null};if(safeGet(view,'getUint16',base+2,little)!==42)return{raw:{},tagCount:0,gps:null};const first=safeGet(view,'getUint32',base+4,little);if(first==null)return{raw:{},tagCount:0,gps:null};
    const out={raw:{},tagCount:0,gps:null};let exifOffset=null,gpsOffset=null;
    const readIfd=(rel,map,bucket)=>{if(rel==null)return;const pos=base+rel;if(pos+2>end)return;const count=safeGet(view,'getUint16',pos,little);if(count==null||count>1024)return;out.tagCount+=count;for(let i=0;i<count;i++){const entry=pos+2+i*12;if(entry+12>end)break;const tag=safeGet(view,'getUint16',entry,little);if(tag==null)continue;const value=readTiffValue(view,base,entry,little,end);if(tag===0x8769&&typeof value==='number')exifOffset=value;if(tag===0x8825&&typeof value==='number')gpsOffset=value;const key=map?.[tag];if(key&&value!=null&&value!==''){out[key]=key==='userComment'?decodeUndefined(value):value;out.raw[bucket+':'+tag.toString(16)]=out[key]}}};
    readIfd(first,TAGS.ifd0,'ifd0');if(exifOffset!=null)readIfd(exifOffset,TAGS.exif,'exif');
    if(gpsOffset!=null){const gps={};const pos=base+gpsOffset;if(pos+2<=end){const count=safeGet(view,'getUint16',pos,little);if(count!=null&&count<=256){out.tagCount+=count;for(let i=0;i<count;i++){const entry=pos+2+i*12;if(entry+12>end)break;const tag=safeGet(view,'getUint16',entry,little),value=readTiffValue(view,base,entry,little,end);if(tag===1)gps.latRef=value;else if(tag===2)gps.lat=value;else if(tag===3)gps.lonRef=value;else if(tag===4)gps.lon=value;else if(tag===5)gps.altRef=value;else if(tag===6)gps.alt=value;else if(tag===7)gps.time=value;else if(tag===18)gps.mapDatum=value;else if(tag===29)gps.date=value}}}
      const decimal=(parts,ref)=>{if(!Array.isArray(parts)||parts.length<3)return null;const vals=parts.slice(0,3).map(x=>x&&typeof x==='object'?x.value:Number(x));if(vals.some(x=>!Number.isFinite(x)))return null;let value=vals[0]+vals[1]/60+vals[2]/3600;if(/^[SW]$/i.test(String(ref||'')))value*=-1;return value};
      const lat=decimal(gps.lat,gps.latRef),lon=decimal(gps.lon,gps.lonRef),altRaw=gps.alt&&typeof gps.alt==='object'?gps.alt.value:Number(gps.alt);if(Number.isFinite(lat)&&Number.isFinite(lon)){let time='';if(Array.isArray(gps.time)&&gps.time.length>=3){const p=gps.time.slice(0,3).map(x=>x&&typeof x==='object'?x.value:Number(x));if(p.every(Number.isFinite))time=p.map(x=>String(Math.round(x)).padStart(2,'0')).join(':')}out.gps={lat,lon,altitude:Number.isFinite(altRaw)?(Number(gps.altRef)===1?-altRaw:altRaw):null,date:String(gps.date||''),time,mapDatum:String(gps.mapDatum||'')}}
    }
    return out;
  }
  function mergeExif(target,incoming){if(!incoming)return;Object.keys(incoming).forEach(key=>{if(key==='raw'||key==='tagCount')return;if(target[key]==null||target[key]==='')target[key]=incoming[key]});target.tagCount=(target.tagCount||0)+(incoming.tagCount||0);target.raw=Object.assign(target.raw||{},incoming.raw||{})}
  function parseJpeg(buffer){const view=new DataView(buffer),bytes=new Uint8Array(buffer),out={format:'JPEG',metaBytes:0,containers:[],text:{},exif:{raw:{},tagCount:0},diagnostic:{segments:0}};if(bytes.length<4||view.getUint16(0,false)!==0xffd8)return out;let pos=2;while(pos+1<bytes.length){if(bytes[pos]!==0xff){pos++;continue}while(pos<bytes.length&&bytes[pos]===0xff)pos++;if(pos>=bytes.length)break;const marker=bytes[pos++];if(marker===0xd9||marker===0xda)break;if(marker===0x01||(marker>=0xd0&&marker<=0xd7))continue;if(pos+2>bytes.length)break;const len=view.getUint16(pos,false);if(len<2||pos+len>bytes.length)break;const payload=pos+2,payloadLen=len-2;out.diagnostic.segments++;if(marker===0xe1){out.metaBytes+=len+2;if(starts(bytes,payload,'Exif\0\0')){out.containers.push('EXIF');mergeExif(out.exif,parseTiff(buffer,payload+6,payloadLen-6))}else if(starts(bytes,payload,'http://ns.adobe.com/xap/1.0/')){out.containers.push('XMP');out.text.xmp=decoder.decode(bytes.subarray(payload,payload+payloadLen)).slice(0,20000)}}else if(marker===0xed){out.metaBytes+=len+2;out.containers.push('IPTC')}else if(marker===0xe2&&starts(bytes,payload,'ICC_PROFILE')){out.metaBytes+=len+2;out.containers.push('ICC')}else if(marker===0xfe){out.metaBytes+=len+2;out.containers.push('Комментарий');out.text.comment=decoder.decode(bytes.subarray(payload,payload+payloadLen)).replace(/\0+$/g,'').trim()}pos+=len}return out}
  function parsePng(buffer){const view=new DataView(buffer),bytes=new Uint8Array(buffer),out={format:'PNG',metaBytes:0,containers:[],text:{},exif:{raw:{},tagCount:0},diagnostic:{chunks:0}};if(bytes.length<8||!starts(bytes,1,'PNG'))return out;let pos=8;while(pos+12<=bytes.length){const len=view.getUint32(pos,false),type=String.fromCharCode(bytes[pos+4],bytes[pos+5],bytes[pos+6],bytes[pos+7]),data=pos+8;if(len>bytes.length-data-4)break;out.diagnostic.chunks++;if(type==='eXIf'){out.metaBytes+=len+12;out.containers.push('EXIF');mergeExif(out.exif,parseTiff(buffer,data,len))}else if(type==='tEXt'||type==='iTXt'||type==='zTXt'){out.metaBytes+=len+12;out.containers.push(type);if(type==='tEXt'){const chunk=bytes.subarray(data,data+len),zero=chunk.indexOf(0);if(zero>0)out.text[decoder.decode(chunk.subarray(0,zero))]=decoder.decode(chunk.subarray(zero+1))}}else if(type==='iCCP'||type==='tIME'){out.metaBytes+=len+12;out.containers.push(type)}pos+=len+12;if(type==='IEND')break}return out}
  function parseWebp(buffer){const view=new DataView(buffer),bytes=new Uint8Array(buffer),out={format:'WebP',metaBytes:0,containers:[],text:{},exif:{raw:{},tagCount:0},diagnostic:{chunks:0}};if(bytes.length<12||!starts(bytes,0,'RIFF')||!starts(bytes,8,'WEBP'))return out;let pos=12;while(pos+8<=bytes.length){const type=String.fromCharCode(bytes[pos],bytes[pos+1],bytes[pos+2],bytes[pos+3]),len=view.getUint32(pos+4,true),data=pos+8;if(len>bytes.length-data)break;out.diagnostic.chunks++;if(type==='EXIF'){out.metaBytes+=len+8;out.containers.push('EXIF');const tiff=starts(bytes,data,'Exif\0\0')?data+6:data;mergeExif(out.exif,parseTiff(buffer,tiff,len-(tiff-data)))}else if(type==='XMP '){out.metaBytes+=len+8;out.containers.push('XMP');out.text.xmp=decoder.decode(bytes.subarray(data,data+len)).slice(0,20000)}else if(type==='ICCP'){out.metaBytes+=len+8;out.containers.push('ICC')}pos+=8+len+(len&1)}return out}
  function parseBuffer(buffer,typeHint){const bytes=new Uint8Array(buffer);if(bytes[0]===0xff&&bytes[1]===0xd8)return parseJpeg(buffer);if(bytes[0]===0x89&&starts(bytes,1,'PNG'))return parsePng(buffer);if(starts(bytes,0,'RIFF')&&starts(bytes,8,'WEBP'))return parseWebp(buffer);return{format:String(typeHint||'').replace('image/','').toUpperCase()||'НЕИЗВЕСТНО',metaBytes:0,containers:[],text:{},exif:{raw:{},tagCount:0},unsupported:true}}
  function pickFromXmp(text,names){if(!text)return'';for(const name of names){const escaped=name.replace(':','\\:'),attr=new RegExp(escaped+'=[\"\']([^\"\']+)[\"\']','i').exec(text);if(attr)return attr[1].trim();const tag=new RegExp('<'+escaped+'[^>]*>([^<]+)</','i').exec(text);if(tag)return tag[1].trim()}return''}
  function rational(value){if(value&&typeof value==='object'&&Number.isFinite(value.value))return value.value;const n=Number(value);return Number.isFinite(n)?n:null}
  const enumText=(value,map)=>value==null?'':(map[value]||String(value));
  function normalizeReport(file,parsed,sourceKind){
    const exif=parsed.exif||{},xmp=parsed.text?.xmp||'',text=parsed.text||{};const camera=[exif.make,exif.model].filter(Boolean).join(' ').trim(),lens=[exif.lensMake,exif.lensModel].filter(Boolean).join(' ').trim();const author=exif.artist||pickFromXmp(xmp,['dc:creator','photoshop:AuthorsPosition'])||text.Author||text.author||'',copyright=exif.copyright||pickFromXmp(xmp,['dc:rights','photoshop:Copyright'])||text.Copyright||text.copyright||'',software=exif.software||pickFromXmp(xmp,['xmp:CreatorTool','tiff:Software'])||text.Software||text.software||'',date=exif.dateOriginal||exif.dateTime||pickFromXmp(xmp,['exif:DateTimeOriginal','xmp:CreateDate'])||text.CreationTime||text['Creation Time']||'',dateDigitized=exif.dateDigitized||pickFromXmp(xmp,['exif:DateTimeDigitized'])||'',comment=exif.userComment||parsed.text?.comment||text.Comment||text.Description||exif.description||pickFromXmp(xmp,['dc:description'])||'';
    const exposure=rational(exif.exposureTime),aperture=rational(exif.fNumber),focal=rational(exif.focalLength),bias=rational(exif.exposureBias),digitalZoom=rational(exif.digitalZoom),isoRaw=Array.isArray(exif.iso)?exif.iso[0]:exif.iso,iso=Number(isoRaw),gps=exif.gps||null;
    const identifiers=[exif.cameraOwner,exif.bodySerial,exif.lensSerial,exif.imageUniqueId].filter(Boolean),warnings=[];if(gps)warnings.push({level:'danger',title:'GPS-координаты',text:'Могут раскрыть точное место съёмки.'});if(identifiers.length)warnings.push({level:'danger',title:'Идентификаторы устройства',text:'Серийные номера или владелец могут связать файл с конкретным устройством.'});if(date||dateDigitized)warnings.push({level:'warn',title:'Дата и время',text:'Позволяют восстановить время съёмки.'});if(author||copyright)warnings.push({level:'warn',title:'Авторство',text:'В файле может находиться имя или подпись автора.'});if(comment)warnings.push({level:'warn',title:'Комментарий',text:'Свободный текст иногда содержит личную информацию.'});
    const risk=warnings.some(x=>x.level==='danger')?'danger':warnings.length?'warn':'safe',riskTitle=risk==='danger'?'Найдены чувствительные метаданные':risk==='warn'?'Есть данные, которые стоит проверить':'Явных приватных данных не найдено';
    const fields={camera,lens,date,dateDigitized,author,copyright,software,comment,gps,exposure,aperture,focal,iso:Number.isFinite(iso)?iso:null,bias,digitalZoom,focal35:exif.focal35||null,orientation:exif.orientation||null,cameraOwner:exif.cameraOwner||'',bodySerial:exif.bodySerial||'',lensSerial:exif.lensSerial||'',imageUniqueId:exif.imageUniqueId||'',pixelWidth:exif.pixelWidth||null,pixelHeight:exif.pixelHeight||null,colorSpace:exif.colorSpace||null,exposureProgram:enumText(exif.exposureProgram,{1:'Ручной',2:'Программный',3:'Приоритет диафрагмы',4:'Приоритет выдержки',5:'Творческий',6:'Спортивный',7:'Портрет',8:'Пейзаж'}),metering:enumText(exif.meteringMode,{1:'Средний',2:'Центровзвешенный',3:'Точечный',5:'Матричный',6:'Частичный'}),flash:enumText(exif.flash,{0:'Не сработала',1:'Сработала',5:'Сработала, без возврата',7:'Сработала, возврат обнаружен',16:'Не сработала'}),whiteBalance:enumText(exif.whiteBalance,{0:'Авто',1:'Ручной'}),exposureMode:enumText(exif.exposureMode,{0:'Авто',1:'Ручной',2:'Автобрекетинг'}),sceneCapture:enumText(exif.sceneCapture,{0:'Стандарт',1:'Пейзаж',2:'Портрет',3:'Ночная сцена'})};
    const knownFields=Object.values(fields).filter(v=>v!==null&&v!==undefined&&v!==''&&!(Array.isArray(v)&&!v.length)).length;
    return{file,sourceKind,format:parsed.format||String(file.type||'image').replace('image/','').toUpperCase(),size:file.size||0,metadataBytes:parsed.metaBytes||0,containers:[...new Set(parsed.containers||[])],tagCount:exif.tagCount||0,knownFields,risk,riskTitle,warnings,source:parsed,...fields};
  }
  async function inspectFile(file,sourceKind){const buffer=await file.arrayBuffer(),parsed=parseBuffer(buffer,file.type);return normalizeReport(file,parsed,sourceKind||'file')}
  async function parseFile(file,sourceKind){const token=++analysisToken;currentFile=file;currentSourceKind=sourceKind||'file';renderLoading(file);try{const next=await inspectFile(file,currentSourceKind);if(token!==analysisToken)return;report=next;render()}catch(error){if(token!==analysisToken)return;console.error('Safelight metadata:',error);report=null;renderError('Не удалось прочитать байты текущего изображения.')}}
  async function fileFromPreview(){const img=$('previewImg'),src=img?.src||'';if(!src)return null;const token=++previewToken;try{const response=await fetch(src,{cache:'no-store'});if(!response.ok&&response.status!==0)throw new Error('HTTP '+response.status);const blob=await response.blob();if(token!==previewToken||$('previewImg')?.src!==src)return null;return new File([blob],fileNameFallback(),{type:blob.type||$('meta-type')?.textContent?.split(' ')[0]||'application/octet-stream',lastModified:Date.now()})}catch(error){console.warn('Safelight metadata preview source:',error);return null}}
  async function analyzeCurrent(){if(currentSourceKind==='file'&&currentFile)return parseFile(currentFile,'file');const file=await fileFromPreview();if(file)return parseFile(file,currentSourceKind==='working'?'working':'preview');if(currentFile)return parseFile(currentFile,'file');report=null;render()}

  function formatExposure(seconds){if(!Number.isFinite(seconds)||seconds<=0)return'';if(seconds>=1)return seconds.toFixed(seconds<10?1:0)+' с';return'1/'+Math.round(1/seconds)+' с'}
  function gpsText(gps){if(!gps)return'';let value=gps.lat.toFixed(6)+', '+gps.lon.toFixed(6);if(Number.isFinite(gps.altitude))value+=' · '+gps.altitude.toFixed(1)+' м';return value}
  function addCopy(key,value,label){if(value==null||value==='')return'';copyValues.set(key,{label:label||key,value:String(value)});return'<button type="button" class="sl-meta-copy" data-meta-copy="'+esc(key)+'" aria-label="Копировать значение" title="Копировать"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></svg></button>'}
  function row(label,value,opts){if(value==null||value==='')return'';opts=opts||{};const key=opts.key||('field-'+copyValues.size);return'<div class="sl-meta-row'+(opts.sensitive?' sensitive':'')+'"><span>'+esc(label)+'</span><div class="sl-meta-value"><b>'+esc(value)+'</b>'+addCopy(key,value,label)+'</div></div>'}
  function section(title,subtitle,content,open){if(!content)return'';return'<div class="sl-meta-section sl-meta-accordion'+(open?' open':'')+'"><button type="button" class="sl-meta-section-head" aria-expanded="'+(open?'true':'false')+'"><span><b>'+esc(title)+'</b><small>'+esc(subtitle)+'</small></span><i aria-hidden="true"></i></button><div class="sl-meta-section-body"'+(open?'':' hidden')+'>'+content+'</div></div>'}
  function categoryState(r){return{gps:!!r.gps,identifiers:!!(r.cameraOwner||r.bodySerial||r.lensSerial||r.imageUniqueId),dates:!!(r.date||r.dateDigitized),author:!!(r.author||r.copyright),comments:!!r.comment,software:!!r.software,camera:!!(r.camera||r.lens),shooting:!!(r.exposure||r.aperture||Number.isFinite(r.iso)||r.focal||r.bias||r.exposureProgram||r.metering||r.flash||r.whiteBalance||r.exposureMode||r.sceneCapture)}}
  const CATEGORY_LABELS={gps:'GPS',identifiers:'Идентификаторы',dates:'Дата и время',author:'Авторство',comments:'Комментарии',software:'Программа',camera:'Камера и объектив',shooting:'Параметры съёмки'};
  function cleanerToggle(key,title,desc,found){return'<label class="sl-meta-toggle'+(found?' found':'')+'"><input type="checkbox" data-meta-remove="'+key+'"><span><b>'+esc(title)+(found?'<em>найдено</em>':'')+'</b><small>'+esc(desc)+'</small></span><i></i></label>'}
  function diagnosticText(r){if(r.source?.unsupported)return'Формат «'+r.format+'» распознан, но глубокий разбор метаданных для него пока не поддерживается.';if(r.containers.length||r.tagCount)return'Найдено контейнеров: '+r.containers.length+' · EXIF-тегов: '+r.tagCount+' · распознано полей: '+r.knownFields+'.';return'Проверено '+fmtBytes(r.size)+'. EXIF/XMP/IPTC/ICC не обнаружены.'}
  function renderLoading(file){const box=$('sl-meta-tool');if(box)box.innerHTML='<div class="sl-meta-empty"><span class="sl-meta-spinner"></span><b>Читаю метаданные</b><small>'+esc(file.name||'текущее изображение')+'</small></div>'}
  function renderError(message){const box=$('sl-meta-tool');if(box)box.innerHTML='<div class="sl-meta-empty error"><b>'+esc(message)+'</b><small>Сам файл остаётся на вашем устройстве.</small></div>'}
  function riskMarkup(r){const text=r.risk==='danger'?'Перед публикацией рекомендуется очистить отмеченные чувствительные поля.':r.risk==='warn'?'Проверьте данные ниже перед публикацией.':'GPS, серийные номера и известные персональные поля не обнаружены.';return'<div class="sl-meta-risk '+r.risk+'"><div class="sl-meta-risk-icon">'+(r.risk==='danger'?'!':r.risk==='warn'?'i':'✓')+'</div><div><b>'+esc(r.riskTitle)+'</b><span>'+esc(text)+'</span></div></div>'+(r.warnings.length?'<div class="sl-meta-alerts">'+r.warnings.map(w=>'<div class="'+w.level+'"><b>'+esc(w.title)+'</b><span>'+esc(w.text)+'</span></div>').join('')+'</div>':'')}
  function render(){
    const box=$('sl-meta-tool');if(!box)return;copyValues.clear();if(!report){box.innerHTML='<div class="sl-meta-empty"><div class="sl-meta-empty-icon">i</div><b>Загрузите изображение</b><small>Safelight прочитает EXIF, GPS и другие метаданные из JPEG, PNG или WebP.</small></div>';return}
    const r=report,shooting=[r.exposure?formatExposure(r.exposure):'',r.aperture?'f/'+r.aperture.toFixed(1):'',Number.isFinite(r.iso)?'ISO '+r.iso:'',r.focal?r.focal.toFixed(r.focal<10?1:0)+' мм':''].filter(Boolean).join(' · ');
    const gps=r.gps?'<div class="sl-meta-gps"><div class="sl-meta-gps-head"><div><span>GPS</span><b>В файле есть геолокация</b></div>'+addCopy('gps',gpsText(r.gps),'GPS')+'</div><strong>'+esc(gpsText(r.gps))+'</strong>'+(r.gps.date||r.gps.time?'<small>'+esc([r.gps.date,r.gps.time].filter(Boolean).join(' · '))+'</small>':'')+'<p>Эти координаты могут указывать точное место съёмки. Для публикации их лучше удалить.</p></div>':'<div class="sl-meta-gps safe"><div class="sl-meta-gps-head"><div><span>GPS</span><b>Координаты не найдены</b></div></div><p>В поддерживаемых EXIF-полях геолокация отсутствует.</p></div>';
    const camera=row('Камера',r.camera,{key:'camera'})+row('Объектив',r.lens,{key:'lens'})+row('Фокусное 35 мм',r.focal35?String(r.focal35)+' мм':'',{key:'focal35'})+row('Ориентация EXIF',r.orientation,{key:'orientation'});
    const shoot=row('Сводка',shooting,{key:'shooting'})+row('Программа экспозиции',r.exposureProgram,{key:'exposureProgram'})+row('Замер',r.metering,{key:'metering'})+row('Вспышка',r.flash,{key:'flash'})+row('Баланс белого',r.whiteBalance,{key:'wb'})+row('Режим экспозиции',r.exposureMode,{key:'exposureMode'})+row('Сцена',r.sceneCapture,{key:'scene'})+row('Коррекция экспозиции',Number.isFinite(r.bias)?(r.bias>0?'+':'')+r.bias.toFixed(2)+' EV':'',{key:'bias'});
    const dates=row('Дата съёмки',r.date,{sensitive:!!r.date,key:'date'})+row('Дата оцифровки',r.dateDigitized,{sensitive:!!r.dateDigitized,key:'dateDigitized'});
    const authors=row('Автор',r.author,{sensitive:!!r.author,key:'author'})+row('Copyright',r.copyright,{sensitive:!!r.copyright,key:'copyright'});
    const ids=row('Владелец камеры',r.cameraOwner,{sensitive:!!r.cameraOwner,key:'owner'})+row('Серийный номер камеры',r.bodySerial,{sensitive:!!r.bodySerial,key:'bodySerial'})+row('Серийный номер объектива',r.lensSerial,{sensitive:!!r.lensSerial,key:'lensSerial'})+row('Image Unique ID',r.imageUniqueId,{sensitive:!!r.imageUniqueId,key:'uid'});
    const software=row('Программа',r.software,{key:'software'})+row('Комментарий / описание',r.comment,{sensitive:!!r.comment,key:'comment'});
    const fileInfo=row('Размер из EXIF',r.pixelWidth&&r.pixelHeight?String(r.pixelWidth)+' × '+String(r.pixelHeight):'',{key:'exifDims'})+row('Цветовое пространство',r.colorSpace,{key:'colorSpace'});
    const found=categoryState(r);
    box.innerHTML=riskMarkup(r)+'<div class="sl-meta-summary"><div><span>Формат</span><b>'+esc(r.format)+'</b></div><div><span>Файл</span><b>'+esc(fmtBytes(r.size))+'</b></div><div><span>Метаданные</span><b>'+esc(fmtBytes(r.metadataBytes))+'</b></div><div><span>EXIF-теги</span><b>'+esc(r.tagCount)+'</b></div></div>'+gps+'<div class="sl-meta-toolbar"><button type="button" class="btn ghost" data-meta-copy-all>Копировать все значения</button><span>'+esc(diagnosticText(r))+'</span></div>'+section('Камера и объектив','модель, оптика и ориентация',camera,!!camera)+section('Параметры съёмки','экспозиция и режимы камеры',shoot,false)+section('Дата и время','временные метки EXIF',dates,false)+section('Авторство','автор и copyright',authors,false)+section('Идентификаторы','поля, связывающие файл с устройством',ids,false)+section('Программа и комментарии','редактор и свободный текст',software,false)+section('Файл','технические поля контейнера',fileInfo,false)+(r.containers.length?'<div class="sl-meta-containers">'+r.containers.map(x=>'<span>'+esc(x)+'</span>').join('')+'</div>':'')+'<div class="sl-meta-section sl-meta-cleaner"><div class="sl-meta-clean-head"><div><b>Очистка метаданных</b><small>Выберите готовый режим или настройте категории вручную.</small></div></div><div class="sl-meta-presets"><button type="button" class="btn ghost" data-meta-preset="gps">Удалить GPS</button><button type="button" class="btn ghost" data-meta-preset="publish">Для публикации</button><button type="button" class="btn ghost" data-meta-preset="all">Удалить всё</button></div><div class="sl-meta-clean-note" id="sl-meta-clean-note">Выберите режим очистки.</div><details class="sl-meta-details"><summary>Точная настройка</summary><div class="sl-meta-toggles">'+cleanerToggle('gps','Геолокация','GPS-координаты, высота и GPS-время',found.gps)+cleanerToggle('identifiers','Идентификаторы','Владелец, серийные номера и Unique ID',found.identifiers)+cleanerToggle('dates','Дата и время','Дата съёмки и оцифровки',found.dates)+cleanerToggle('author','Авторство','Автор и copyright',found.author)+cleanerToggle('comments','Комментарии','Комментарий и описание',found.comments)+cleanerToggle('software','Программа','Название редактора или приложения',found.software)+cleanerToggle('camera','Камера и объектив','Производитель и модель камеры/объектива',found.camera)+cleanerToggle('shooting','Параметры съёмки','ISO, выдержка, диафрагма, фокусное и режимы',found.shooting)+'</div></details><div id="sl-meta-clean-report" class="sl-meta-clean-report" hidden></div></div>';
    applyPreset('publish',false);updateCleanerNote();
  }

  function removalState(){const state={gps:false,identifiers:false,dates:false,author:false,comments:false,software:false,camera:false,shooting:false};document.querySelectorAll('#sl-meta-tool [data-meta-remove]').forEach(el=>state[el.dataset.metaRemove]=!!el.checked);return state}
  function applyPreset(name,showStatus){const state={gps:false,identifiers:false,dates:false,author:false,comments:false,software:false,camera:false,shooting:false};if(name==='gps')state.gps=true;else if(name==='publish')Object.assign(state,{gps:true,identifiers:true,dates:true,author:true,comments:true,software:true});else if(name==='all')Object.keys(state).forEach(k=>state[k]=true);document.querySelectorAll('#sl-meta-tool [data-meta-remove]').forEach(el=>el.checked=!!state[el.dataset.metaRemove]);document.querySelectorAll('#sl-meta-tool [data-meta-preset]').forEach(btn=>btn.classList.toggle('active',btn.dataset.metaPreset===name));updateCleanerNote();if(showStatus)flashMetaStatus(name==='gps'?'Удалится только геолокация.':name==='publish'?'Подготовлено для публикации. Камера и параметры съёмки сохранятся в JPEG.':'Будут удалены все поддерживаемые метаданные.')}
  function updateCleanerNote(){const note=$('sl-meta-clean-note');if(!note)return;const remove=removalState(),selected=Object.keys(remove).filter(k=>remove[k]),format=String(report?.format||'').toUpperCase();if(!selected.length)note.textContent='Категории не выбраны для удаления.';else if(format==='PNG'||format==='WEBP')note.textContent='При экспорте '+format+' браузер создаёт новую чистую копию: все метаданные будут удалены независимо от выбранных категорий.';else note.textContent='JPEG: удалить '+selected.map(k=>CATEGORY_LABELS[k]).join(', ')+'. Неотмеченные поддерживаемые поля будут сохранены.'}
  function copyAllText(){if(!report)return'';const parts=[];copyValues.forEach(item=>parts.push(item.label+': '+item.value));return parts.join('\n')}
  async function copyText(text){try{await navigator.clipboard.writeText(text)}catch(_){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}}
  function flashMetaStatus(text){const status=$('meta-status')||$('sl-export-hint');if(!status)return;status.textContent=text;status.classList.add('show');clearTimeout(flashMetaStatus.t);flashMetaStatus.t=setTimeout(()=>status.classList.remove('show'),2600)}
  function bindPanelEvents(box){if(box.dataset.bound==='1')return;box.dataset.bound='1';box.addEventListener('click',async event=>{const copy=event.target.closest('[data-meta-copy]');if(copy){event.preventDefault();const item=copyValues.get(copy.dataset.metaCopy);if(item?.value){await copyText(item.value);copy.classList.add('copied');setTimeout(()=>copy.classList.remove('copied'),700)}return}if(event.target.closest('[data-meta-copy-all]')){event.preventDefault();await copyText(copyAllText());flashMetaStatus('Значения скопированы.');return}const head=event.target.closest('.sl-meta-section-head');if(head){event.preventDefault();const section=head.closest('.sl-meta-accordion'),body=section?.querySelector('.sl-meta-section-body'),open=head.getAttribute('aria-expanded')==='true';if(section&&body){section.classList.toggle('open',!open);head.setAttribute('aria-expanded',open?'false':'true');body.hidden=open}return}const preset=event.target.closest('[data-meta-preset]');if(preset){event.preventDefault();applyPreset(preset.dataset.metaPreset,true);return}});box.addEventListener('change',event=>{if(event.target.matches('[data-meta-remove]')){document.querySelectorAll('#sl-meta-tool [data-meta-preset]').forEach(btn=>btn.classList.remove('active'));updateCleanerNote()}})}

  function asciiBytes(text){return[...encoder.encode(String(text||'')),0]}
  function uintBytes(value,bytes){const arr=new Uint8Array(bytes),view=new DataView(arr.buffer);if(bytes===2)view.setUint16(0,Math.max(0,Math.round(value||0)),true);else if(bytes===4)view.setUint32(0,Math.max(0,Math.round(value||0)),true);else arr[0]=Math.max(0,Math.round(value||0))&255;return[...arr]}
  function rationalBytes(value){if(!Number.isFinite(value))return[];const den=1000000;return[...uintBytes(Math.round(value*den),4),...uintBytes(den,4)]}
  function rationalsBytes(values){return values.flatMap(rationalBytes)}
  function decimalToGps(value){const abs=Math.abs(value),deg=Math.floor(abs),mfloat=(abs-deg)*60,min=Math.floor(mfloat),sec=(mfloat-min)*60;return[deg,min,sec]}
  function makeEntry(tag,type,count,bytes){return{tag,type,count,bytes:Array.from(bytes||[])}}
  function buildExifPayload(meta,remove){
    if(!meta)return null;const ifd0=[],exif=[],gps=[],src=meta.source?.exif||{};
    if(!remove.camera){if(src.make){const b=asciiBytes(src.make);ifd0.push(makeEntry(0x010f,2,b.length,b))}if(src.model){const b=asciiBytes(src.model);ifd0.push(makeEntry(0x0110,2,b.length,b))}if(src.lensMake){const b=asciiBytes(src.lensMake);exif.push(makeEntry(0xa433,2,b.length,b))}if(src.lensModel){const b=asciiBytes(src.lensModel);exif.push(makeEntry(0xa434,2,b.length,b))}}
    if(!remove.identifiers){if(meta.cameraOwner){const b=asciiBytes(meta.cameraOwner);exif.push(makeEntry(0xa430,2,b.length,b))}if(meta.bodySerial){const b=asciiBytes(meta.bodySerial);exif.push(makeEntry(0xa431,2,b.length,b))}if(meta.lensSerial){const b=asciiBytes(meta.lensSerial);exif.push(makeEntry(0xa435,2,b.length,b))}if(meta.imageUniqueId){const b=asciiBytes(meta.imageUniqueId);exif.push(makeEntry(0xa420,2,b.length,b))}}
    if(!remove.software&&meta.software){const b=asciiBytes(meta.software);ifd0.push(makeEntry(0x0131,2,b.length,b))}
    if(!remove.comments&&meta.comment){const b=asciiBytes(meta.comment);ifd0.push(makeEntry(0x010e,2,b.length,b))}
    if(!remove.author){if(meta.author){const b=asciiBytes(meta.author);ifd0.push(makeEntry(0x013b,2,b.length,b))}if(meta.copyright){const b=asciiBytes(meta.copyright);ifd0.push(makeEntry(0x8298,2,b.length,b))}}
    if(!remove.dates&&meta.date){const b=asciiBytes(meta.date);ifd0.push(makeEntry(0x0132,2,b.length,b));exif.push(makeEntry(0x9003,2,b.length,b))}
    if(!remove.shooting){if(meta.exposure)exif.push(makeEntry(0x829a,5,1,rationalBytes(meta.exposure)));if(meta.aperture)exif.push(makeEntry(0x829d,5,1,rationalBytes(meta.aperture)));if(Number.isFinite(meta.iso))exif.push(makeEntry(0x8827,3,1,uintBytes(meta.iso,2)));if(meta.focal)exif.push(makeEntry(0x920a,5,1,rationalBytes(meta.focal)))}
    if(!remove.gps&&meta.gps){const lat=decimalToGps(meta.gps.lat),lon=decimalToGps(meta.gps.lon);gps.push(makeEntry(1,2,2,asciiBytes(meta.gps.lat<0?'S':'N')));gps.push(makeEntry(2,5,3,rationalsBytes(lat)));gps.push(makeEntry(3,2,2,asciiBytes(meta.gps.lon<0?'W':'E')));gps.push(makeEntry(4,5,3,rationalsBytes(lon)));if(Number.isFinite(meta.gps.altitude)){gps.push(makeEntry(5,1,1,[meta.gps.altitude<0?1:0]));gps.push(makeEntry(6,5,1,rationalBytes(Math.abs(meta.gps.altitude))))}}
    if(!ifd0.length&&!exif.length&&!gps.length)return null;if(exif.length)ifd0.push(makeEntry(0x8769,4,1,[0,0,0,0]));if(gps.length)ifd0.push(makeEntry(0x8825,4,1,[0,0,0,0]));ifd0.sort((a,b)=>a.tag-b.tag);exif.sort((a,b)=>a.tag-b.tag);gps.sort((a,b)=>a.tag-b.tag);const tableLen=entries=>2+entries.length*12+4,ifd0Offset=8,exifOffset=exif.length?ifd0Offset+tableLen(ifd0):0,gpsOffset=gps.length?ifd0Offset+tableLen(ifd0)+tableLen(exif):0,dataStart=ifd0Offset+tableLen(ifd0)+tableLen(exif)+tableLen(gps);ifd0.forEach(entry=>{if(entry.tag===0x8769)entry.bytes=uintBytes(exifOffset,4);if(entry.tag===0x8825)entry.bytes=uintBytes(gpsOffset,4)});const extra=[...ifd0,...exif,...gps].reduce((sum,e)=>sum+(e.bytes.length>4?e.bytes.length+(e.bytes.length&1):0),0),tiff=new Uint8Array(dataStart+extra),view=new DataView(tiff.buffer);tiff[0]=0x49;tiff[1]=0x49;view.setUint16(2,42,true);view.setUint32(4,ifd0Offset,true);let cursor=dataStart;const writeIfd=(entries,offset)=>{if(!entries.length||!offset)return;view.setUint16(offset,entries.length,true);entries.forEach((entry,index)=>{const p=offset+2+index*12;view.setUint16(p,entry.tag,true);view.setUint16(p+2,entry.type,true);view.setUint32(p+4,entry.count,true);if(entry.bytes.length<=4){for(let i=0;i<4;i++)tiff[p+8+i]=entry.bytes[i]||0}else{view.setUint32(p+8,cursor,true);tiff.set(entry.bytes,cursor);cursor+=entry.bytes.length;if(cursor&1)cursor++}});view.setUint32(offset+2+entries.length*12,0,true)};writeIfd(ifd0,ifd0Offset);writeIfd(exif,exifOffset);writeIfd(gps,gpsOffset);const prefix=encoder.encode('Exif\0\0'),payload=new Uint8Array(prefix.length+tiff.length);payload.set(prefix);payload.set(tiff,prefix.length);return payload;
  }
  async function injectExif(jpegBlob,payload){if(!payload)return jpegBlob;const source=new Uint8Array(await jpegBlob.arrayBuffer());if(source.length<4||source[0]!==0xff||source[1]!==0xd8)return jpegBlob;const segLen=payload.length+2;if(segLen>65535)return jpegBlob;const segment=new Uint8Array(payload.length+4);segment[0]=0xff;segment[1]=0xe1;segment[2]=(segLen>>8)&255;segment[3]=segLen&255;segment.set(payload,4);let insert=2;if(source.length>6&&source[2]===0xff&&source[3]===0xe0){const len=(source[4]<<8)|source[5];if(len>=2&&4+len<=source.length)insert=4+len}const out=new Uint8Array(source.length+segment.length);out.set(source.subarray(0,insert));out.set(segment,insert);out.set(source.subarray(insert),insert+segment.length);return new Blob([out],{type:'image/jpeg'})}
  async function canvasFromPreview(){const img=$('previewImg');if(!img?.src)throw new Error('Сначала загрузите изображение');if(!img.complete||!img.naturalWidth)await new Promise((resolve,reject)=>{const ok=()=>{cleanup();resolve()},bad=()=>{cleanup();reject(new Error('Предпросмотр ещё не готов'))},cleanup=()=>{img.removeEventListener('load',ok);img.removeEventListener('error',bad)};img.addEventListener('load',ok,{once:true});img.addEventListener('error',bad,{once:true})});const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);return canvas}
  function canvasBlob(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Не удалось подготовить файл')),type,quality))}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),4000)}
  function baseName(){return(currentFile?.name||fileNameFallback()||'safelight').replace(/\.[^.]+$/,'').trim()||'safelight'}
  async function verifyOutput(blob,name){const file=new File([blob],name,{type:blob.type,lastModified:Date.now()});return inspectFile(file,'export')}
  function renderCleanReport(before,after,remove,format,name){const box=$('sl-meta-clean-report');if(!box)return;const beforeFound=categoryState(before),afterFound=categoryState(after),removed=Object.keys(remove).filter(k=>remove[k]&&beforeFound[k]).map(k=>CATEGORY_LABELS[k]),preserved=Object.keys(remove).filter(k=>!remove[k]&&beforeFound[k]).map(k=>CATEGORY_LABELS[k]),verified=Object.keys(remove).every(k=>!remove[k]||!afterFound[k]);box.hidden=false;box.className='sl-meta-clean-report '+(verified?'ok':'warn');box.innerHTML='<div class="sl-meta-clean-report-head"><b>'+(verified?'Очистка проверена':'Проверьте результат')+'</b><span>'+esc(name)+'</span></div><div class="sl-meta-clean-stats"><div><span>Метаданные до</span><b>'+esc(fmtBytes(before.metadataBytes))+'</b></div><div><span>После</span><b>'+esc(fmtBytes(after.metadataBytes))+'</b></div><div><span>GPS</span><b>'+(after.gps?'остался':'нет')+'</b></div></div><p>Удалено: '+esc(removed.length?removed.join(', '):'ничего из найденного')+'.'+(format==='jpeg'&&preserved.length?' Сохранено: '+esc(preserved.join(', '))+'.':'')+'</p><small>Safelight повторно разобрал созданный файл после экспорта. Контейнеры после очистки: '+esc(after.containers.length?after.containers.join(', '):'нет')+'.</small>'}
  async function exportMetadata(format){if(exportBusy)return;exportBusy=true;try{const canvas=await canvasFromPreview(),remove=removalState();let before=report;if(!before){const srcFile=await fileFromPreview();if(srcFile)before=await inspectFile(srcFile,'preview')}if(!before)throw new Error('Инспектор метаданных ещё не готов');let blob,name;if(format==='jpeg'){const opaque=document.createElement('canvas');opaque.width=canvas.width;opaque.height=canvas.height;const ctx=opaque.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,opaque.width,opaque.height);ctx.drawImage(canvas,0,0);blob=await canvasBlob(opaque,'image/jpeg',.94);const payload=buildExifPayload(before,remove);if(payload)blob=await injectExif(blob,payload);name=baseName()+'-clean.jpg'}else if(format==='webp'){blob=await canvasBlob(canvas,'image/webp',.92);name=baseName()+'-clean.webp'}else if(format==='png'){blob=await canvasBlob(canvas,'image/png');name=baseName()+'-clean.png'}else throw new Error('Выберите JPEG, WebP или PNG');const after=await verifyOutput(blob,name);renderCleanReport(before,after,remove,format,name);download(blob,name);flashMetaStatus('Файл очищен и проверен.')}finally{exportBusy=false}}

  function installPanel(){const panel=$('panel-metadata');if(!panel)return false;const card=panel.querySelector('.panel-card');if(!card)return false;if(!$('sl-meta-tool'))card.innerHTML='<div id="sl-meta-tool" class="sl-meta-tool"></div><div class="status-line" id="meta-status"></div>';bindPanelEvents($('sl-meta-tool'));render();return true}
  function captureFile(file){if(!file)return;if(file.type.startsWith('image/')||/\.(jpe?g|png|webp|heic|heif)$/i.test(file.name||'')){currentFile=file;currentSourceKind='file';parseFile(file,'file')}}
  document.addEventListener('change',event=>{if(event.target?.id!=='fileInput')return;const file=event.target.files?.[0];if(file)captureFile(file)},true);
  document.addEventListener('drop',event=>{const file=[...(event.dataTransfer?.files||[])].find(f=>f.type.startsWith('image/')||/\.(jpe?g|png|webp|heic|heif)$/i.test(f.name||''));if(file)captureFile(file)},true);
  window.addEventListener('safelight:source-file',()=>{currentSourceKind='file';if(currentFile)setTimeout(()=>parseFile(currentFile,'file'),0);else setTimeout(analyzeCurrent,0)});
  window.addEventListener('safelight:working-source',()=>{currentSourceKind='working';currentFile=null;analysisToken++;if(active())setTimeout(analyzeCurrent,0)});
  window.addEventListener('safelight:toolchange',event=>{if(event.detail?.page!=='metadata')return;setTimeout(analyzeCurrent,0)});
  const preview=$('previewImg');if(preview)new MutationObserver(()=>{if(currentSourceKind==='working'&&active())setTimeout(analyzeCurrent,0)}).observe(preview,{attributes:true,attributeFilter:['src']});
  window.safelightMetadataExportItems=()=>[{value:'jpeg',label:'JPEG',meta:'выборочная очистка'},{value:'webp',label:'WebP',meta:'чистый файл'},{value:'png',label:'PNG',meta:'чистый файл'}];
  window.safelightMetadataExport=exportMetadata;window.safelightAnalyzeMetadataFile=file=>parseFile(file,'file');window.safelightMetadataInspector=Object.freeze({getReport:()=>report?{...report}:null,applyPreset:name=>applyPreset(name,true)});
  function boot(){if(!installPanel()){setTimeout(boot,50);return}const input=$('fileInput');if(input?.files?.[0])captureFile(input.files[0]);else if($('previewImg')?.src)setTimeout(analyzeCurrent,0)}
  boot();
})();
